/*********** GENERATED - DO NOT MODIFY ***********/
package sxr.invoice.ubl.codes;

public enum Uncl1153 {
	P_AAA("AAA", "Order acknowledgement document identifier"),
	P_AAB("AAB", "Proforma invoice document identifier"),
	P_AAC("AAC", "Documentary credit identifier"),
	P_AAD("AAD", "Contract document addendum identifier"),
	P_AAE("AAE", "Goods declaration number"),
	P_AAF("AAF", "Debit card number"),
	P_AAG("AAG", "Offer number"),
	P_AAH("AAH", "Bank's batch interbank transaction reference number"),
	P_AAI("AAI", "Bank's individual interbank transaction reference number"),
	P_AAJ("AAJ", "Delivery order number"),
	P_AAK("AAK", "Despatch advice number"),
	P_AAL("AAL", "Drawing number"),
	P_AAM("AAM", "Waybill number"),
	P_AAN("AAN", "Delivery schedule number"),
	P_AAO("AAO", "Consignment identifier, consignee assigned"),
	P_AAP("AAP", "Partial shipment identifier"),
	P_AAQ("AAQ", "Transport equipment identifier"),
	P_AAR("AAR", "Municipality assigned business registry number"),
	P_AAS("AAS", "Transport contract document identifier"),
	P_AAT("AAT", "Master label number"),
	P_AAU("AAU", "Despatch note document identifier"),
	P_AAV("AAV", "Enquiry number"),
	P_AAW("AAW", "Docket number"),
	P_AAX("AAX", "Civil action number"),
	P_AAY("AAY", "Carrier's agent reference number"),
	P_AAZ("AAZ", "Standard Carrier Alpha Code (SCAC) number"),
	P_ABA("ABA", "Customs valuation decision number"),
	P_ABB("ABB", "End use authorization number"),
	P_ABC("ABC", "Anti-dumping case number"),
	P_ABD("ABD", "Customs tariff number"),
	P_ABE("ABE", "Declarant's reference number"),
	P_ABF("ABF", "Repair estimate number"),
	P_ABG("ABG", "Customs decision request number"),
	P_ABH("ABH", "Sub-house bill of lading number"),
	P_ABI("ABI", "Tax payment identifier"),
	P_ABJ("ABJ", "Quota number"),
	P_ABK("ABK", "Transit (onward carriage) guarantee (bond) number"),
	P_ABL("ABL", "Customs guarantee number"),
	P_ABM("ABM", "Replacing part number"),
	P_ABN("ABN", "Seller's catalogue number"),
	P_ABO("ABO", "Originator's reference"),
	P_ABP("ABP", "Declarant's Customs identity number"),
	P_ABQ("ABQ", "Importer reference number"),
	P_ABR("ABR", "Export clearance instruction reference number"),
	P_ABS("ABS", "Import clearance instruction reference number"),
	P_ABT("ABT", "Goods declaration document identifier, Customs"),
	P_ABU("ABU", "Article number"),
	P_ABV("ABV", "Intra-plant routing"),
	P_ABW("ABW", "Stock keeping unit number"),
	P_ABX("ABX", "Text Element Identifier deletion reference"),
	P_ABY("ABY", "Allotment identification (Air)"),
	P_ABZ("ABZ", "Vehicle licence number"),
	P_AC("AC", "Air cargo transfer manifest"),
	P_ACA("ACA", "Cargo acceptance order reference number"),
	P_ACB("ACB", "US government agency number"),
	P_ACC("ACC", "Shipping unit identification"),
	P_ACD("ACD", "Additional reference number"),
	P_ACE("ACE", "Related document number"),
	P_ACF("ACF", "Addressee reference"),
	P_ACG("ACG", "ATA carnet number"),
	P_ACH("ACH", "Packaging unit identification"),
	P_ACI("ACI", "Outerpackaging unit identification"),
	P_ACJ("ACJ", "Customer material specification number"),
	P_ACK("ACK", "Bank reference"),
	P_ACL("ACL", "Principal reference number"),
	P_ACN("ACN", "Collection advice document identifier"),
	P_ACO("ACO", "Iron charge number"),
	P_ACP("ACP", "Hot roll number"),
	P_ACQ("ACQ", "Cold roll number"),
	P_ACR("ACR", "Railway wagon number"),
	P_ACT("ACT", "Unique claims reference number of the sender"),
	P_ACU("ACU", "Loss/event number"),
	P_ACV("ACV", "Estimate order reference number"),
	P_ACW("ACW", "Reference number to previous message"),
	P_ACX("ACX", "Banker's acceptance"),
	P_ACY("ACY", "Duty memo number"),
	P_ACZ("ACZ", "Equipment transport charge number"),
	P_ADA("ADA", "Buyer's item number"),
	P_ADB("ADB", "Matured certificate of deposit"),
	P_ADC("ADC", "Loan"),
	P_ADD("ADD", "Analysis number/test number"),
	P_ADE("ADE", "Account number"),
	P_ADF("ADF", "Treaty number"),
	P_ADG("ADG", "Catastrophe number"),
	P_ADI("ADI", "Bureau signing (statement reference)"),
	P_ADJ("ADJ", "Company / syndicate reference 1"),
	P_ADK("ADK", "Company / syndicate reference 2"),
	P_ADL("ADL", "Ordering customer consignment reference number"),
	P_ADM("ADM", "Shipowner's authorization number"),
	P_ADN("ADN", "Inland transport order number"),
	P_ADO("ADO", "Container work order reference number"),
	P_ADP("ADP", "Statement number"),
	P_ADQ("ADQ", "Unique market reference"),
	P_ADT("ADT", "Group accounting"),
	P_ADU("ADU", "Broker reference 1"),
	P_ADV("ADV", "Broker reference 2"),
	P_ADW("ADW", "Lloyd's claims office reference"),
	P_ADX("ADX", "Secure delivery terms and conditions agreement reference"),
	P_ADY("ADY", "Report number"),
	P_ADZ("ADZ", "Trader account number"),
	P_AE("AE", "Authorization for expense (AFE) number"),
	P_AEA("AEA", "Government agency reference number"),
	P_AEB("AEB", "Assembly number"),
	P_AEC("AEC", "Symbol number"),
	P_AED("AED", "Commodity number"),
	P_AEE("AEE", "Eur 1 certificate number"),
	P_AEF("AEF", "Customer process specification number"),
	P_AEG("AEG", "Customer specification number"),
	P_AEH("AEH", "Applicable instructions or standards"),
	P_AEI("AEI", "Registration number of previous Customs declaration"),
	P_AEJ("AEJ", "Post-entry reference"),
	P_AEK("AEK", "Payment order number"),
	P_AEL("AEL", "Delivery number (transport)"),
	P_AEM("AEM", "Transport route"),
	P_AEN("AEN", "Customer's unit inventory number"),
	P_AEO("AEO", "Product reservation number"),
	P_AEP("AEP", "Project number"),
	P_AEQ("AEQ", "Drawing list number"),
	P_AER("AER", "Project specification number"),
	P_AES("AES", "Primary reference"),
	P_AET("AET", "Request for cancellation number"),
	P_AEU("AEU", "Supplier's control number"),
	P_AEV("AEV", "Shipping note number"),
	P_AEW("AEW", "Empty container bill number"),
	P_AEX("AEX", "Non-negotiable maritime transport document number"),
	P_AEY("AEY", "Substitute air waybill number"),
	P_AEZ("AEZ", "Despatch note (post parcels) number"),
	P_AF("AF", "Airlines flight identification number"),
	P_AFA("AFA", "Through bill of lading number"),
	P_AFB("AFB", "Cargo manifest number"),
	P_AFC("AFC", "Bordereau number"),
	P_AFD("AFD", "Customs item number"),
	P_AFE("AFE", "Export Control Commodity number (ECCN)"),
	P_AFF("AFF", "Marking/label reference"),
	P_AFG("AFG", "Tariff number"),
	P_AFH("AFH", "Replenishment purchase order number"),
	P_AFI("AFI", "Immediate transportation no. for in bond movement"),
	P_AFJ("AFJ", "Transportation exportation no. for in bond movement"),
	P_AFK("AFK", "Immediate exportation no. for in bond movement"),
	P_AFL("AFL", "Associated invoices"),
	P_AFM("AFM", "Secondary Customs reference"),
	P_AFN("AFN", "Account party's reference"),
	P_AFO("AFO", "Beneficiary's reference"),
	P_AFP("AFP", "Second beneficiary's reference"),
	P_AFQ("AFQ", "Applicant's bank reference"),
	P_AFR("AFR", "Issuing bank's reference"),
	P_AFS("AFS", "Beneficiary's bank reference"),
	P_AFT("AFT", "Direct payment valuation number"),
	P_AFU("AFU", "Direct payment valuation request number"),
	P_AFV("AFV", "Quantity valuation number"),
	P_AFW("AFW", "Quantity valuation request number"),
	P_AFX("AFX", "Bill of quantities number"),
	P_AFY("AFY", "Payment valuation number"),
	P_AFZ("AFZ", "Situation number"),
	P_AGA("AGA", "Agreement to pay number"),
	P_AGB("AGB", "Contract party reference number"),
	P_AGC("AGC", "Account party's bank reference"),
	P_AGD("AGD", "Agent's bank reference"),
	P_AGE("AGE", "Agent's reference"),
	P_AGF("AGF", "Applicant's reference"),
	P_AGG("AGG", "Dispute number"),
	P_AGH("AGH", "Credit rating agency's reference number"),
	P_AGI("AGI", "Request number"),
	P_AGJ("AGJ", "Single transaction sequence number"),
	P_AGK("AGK", "Application reference number"),
	P_AGL("AGL", "Delivery verification certificate"),
	P_AGM("AGM", "Number of temporary importation document"),
	P_AGN("AGN", "Reference number quoted on statement"),
	P_AGO("AGO", "Sender's reference to the original message"),
	P_AGP("AGP", "Company issued equipment ID"),
	P_AGQ("AGQ", "Domestic flight number"),
	P_AGR("AGR", "International flight number"),
	P_AGS("AGS", "Employer identification number of service bureau"),
	P_AGT("AGT", "Service group identification number"),
	P_AGU("AGU", "Member number"),
	P_AGV("AGV", "Previous member number"),
	P_AGW("AGW", "Scheme/plan number"),
	P_AGX("AGX", "Previous scheme/plan number"),
	P_AGY("AGY", "Receiving party's member identification"),
	P_AGZ("AGZ", "Payroll number"),
	P_AHA("AHA", "Packaging specification number"),
	P_AHB("AHB", "Authority issued equipment identification"),
	P_AHC("AHC", "Training flight number"),
	P_AHD("AHD", "Fund code number"),
	P_AHE("AHE", "Signal code number"),
	P_AHF("AHF", "Major force program number"),
	P_AHG("AHG", "Nomination number"),
	P_AHH("AHH", "Laboratory registration number"),
	P_AHI("AHI", "Transport contract reference number"),
	P_AHJ("AHJ", "Payee's reference number"),
	P_AHK("AHK", "Payer's reference number"),
	P_AHL("AHL", "Creditor's reference number"),
	P_AHM("AHM", "Debtor's reference number"),
	P_AHN("AHN", "Joint venture reference number"),
	P_AHO("AHO", "Chamber of Commerce registration number"),
	P_AHP("AHP", "Tax registration number"),
	P_AHQ("AHQ", "Wool identification number"),
	P_AHR("AHR", "Wool tax reference number"),
	P_AHS("AHS", "Meat processing establishment registration number"),
	P_AHT("AHT", "Quarantine/treatment status reference number"),
	P_AHU("AHU", "Request for quote number"),
	P_AHV("AHV", "Manual processing authority number"),
	P_AHX("AHX", "Rate note number"),
	P_AHY("AHY", "Freight Forwarder number"),
	P_AHZ("AHZ", "Customs release code"),
	P_AIA("AIA", "Compliance code number"),
	P_AIB("AIB", "Department of transportation bond number"),
	P_AIC("AIC", "Export establishment number"),
	P_AID("AID", "Certificate of conformity"),
	P_AIE("AIE", "Ministerial certificate of homologation"),
	P_AIF("AIF", "Previous delivery instruction number"),
	P_AIG("AIG", "Passport number"),
	P_AIH("AIH", "Common transaction reference number"),
	P_AII("AII", "Bank's common transaction reference number"),
	P_AIJ("AIJ", "Customer's individual transaction reference number"),
	P_AIK("AIK", "Bank's individual transaction reference number"),
	P_AIL("AIL", "Customer's common transaction reference number"),
	P_AIM("AIM", "Individual transaction reference number"),
	P_AIN("AIN", "Product sourcing agreement number"),
	P_AIO("AIO", "Customs transhipment number"),
	P_AIP("AIP", "Customs preference inquiry number"),
	P_AIQ("AIQ", "Packing plant number"),
	P_AIR("AIR", "Original certificate number"),
	P_AIS("AIS", "Processing plant number"),
	P_AIT("AIT", "Slaughter plant number"),
	P_AIU("AIU", "Charge card account number"),
	P_AIV("AIV", "Event reference number"),
	P_AIW("AIW", "Transport section reference number"),
	P_AIX("AIX", "Referred product for mechanical analysis"),
	P_AIY("AIY", "Referred product for chemical analysis"),
	P_AIZ("AIZ", "Consolidated invoice number"),
	P_AJA("AJA", "Part reference indicator in a drawing"),
	P_AJB("AJB", "U.S. Code of Federal Regulations (CFR)"),
	P_AJC("AJC", "Purchasing activity clause number"),
	P_AJD("AJD", "U.S. Defense Federal Acquisition Regulation Supplement"),
	P_AJE("AJE", "Agency clause number"),
	P_AJF("AJF", "Circular publication number"),
	P_AJG("AJG", "U.S. Federal Acquisition Regulation"),
	P_AJH("AJH", "U.S. General Services Administration Regulation"),
	P_AJI("AJI", "U.S. Federal Information Resources Management Regulation"),
	P_AJJ("AJJ", "Paragraph"),
	P_AJK("AJK", "Special instructions number"),
	P_AJL("AJL", "Site specific procedures, terms, and conditions number"),
	P_AJM("AJM", "Master solicitation procedures, terms, and conditions"),
	P_AJN("AJN", "U.S. Department of Veterans Affairs Acquisition Regulation"),
	P_AJO("AJO", "Military Interdepartmental Purchase Request (MIPR) number"),
	P_AJP("AJP", "Foreign military sales number"),
	P_AJQ("AJQ", "Defense priorities allocation system priority rating"),
	P_AJR("AJR", "Wage determination number"),
	P_AJS("AJS", "Agreement number"),
	P_AJT("AJT", "Standard Industry Classification (SIC) number"),
	P_AJU("AJU", "End item number"),
	P_AJV("AJV", "Federal supply schedule item number"),
	P_AJW("AJW", "Technical document number"),
	P_AJX("AJX", "Technical order number"),
	P_AJY("AJY", "Suffix"),
	P_AJZ("AJZ", "Transportation account number"),
	P_AKA("AKA", "Container disposition order reference number"),
	P_AKB("AKB", "Container prefix"),
	P_AKC("AKC", "Transport equipment return reference"),
	P_AKD("AKD", "Transport equipment survey reference"),
	P_AKE("AKE", "Transport equipment survey report number"),
	P_AKF("AKF", "Transport equipment stuffing order"),
	P_AKG("AKG", "Vehicle Identification Number (VIN)"),
	P_AKH("AKH", "Government bill of lading"),
	P_AKI("AKI", "Ordering customer's second reference number"),
	P_AKJ("AKJ", "Direct debit reference"),
	P_AKK("AKK", "Meter reading at the beginning of the delivery"),
	P_AKL("AKL", "Meter reading at the end of delivery"),
	P_AKM("AKM", "Replenishment purchase order range start number"),
	P_AKN("AKN", "Third bank's reference"),
	P_AKO("AKO", "Action authorization number"),
	P_AKP("AKP", "Appropriation number"),
	P_AKQ("AKQ", "Product change authority number"),
	P_AKR("AKR", "General cargo consignment reference number"),
	P_AKS("AKS", "Catalogue sequence number"),
	P_AKT("AKT", "Forwarding order number"),
	P_AKU("AKU", "Transport equipment survey reference number"),
	P_AKV("AKV", "Lease contract reference"),
	P_AKW("AKW", "Transport costs reference number"),
	P_AKX("AKX", "Transport equipment stripping order"),
	P_AKY("AKY", "Prior policy number"),
	P_AKZ("AKZ", "Policy number"),
	P_ALA("ALA", "Procurement budget number"),
	P_ALB("ALB", "Domestic inventory management code"),
	P_ALC("ALC", "Customer reference number assigned to previous balance of"),
	P_ALD("ALD", "Previous credit advice reference number"),
	P_ALE("ALE", "Reporting form number"),
	P_ALF("ALF", "Authorization number for exception to dangerous goods"),
	P_ALG("ALG", "Dangerous goods security number"),
	P_ALH("ALH", "Dangerous goods transport licence number"),
	P_ALI("ALI", "Previous rental agreement number"),
	P_ALJ("ALJ", "Next rental agreement reason number"),
	P_ALK("ALK", "Consignee's invoice number"),
	P_ALL("ALL", "Message batch number"),
	P_ALM("ALM", "Previous delivery schedule number"),
	P_ALN("ALN", "Physical inventory recount reference number"),
	P_ALO("ALO", "Receiving advice number"),
	P_ALP("ALP", "Returnable container reference number"),
	P_ALQ("ALQ", "Returns notice number"),
	P_ALR("ALR", "Sales forecast number"),
	P_ALS("ALS", "Sales report number"),
	P_ALT("ALT", "Previous tax control number"),
	P_ALU("ALU", "AGERD (Aerospace Ground Equipment Requirement Data) number"),
	P_ALV("ALV", "Registered capital reference"),
	P_ALW("ALW", "Standard number of inspection document"),
	P_ALX("ALX", "Model"),
	P_ALY("ALY", "Financial management reference"),
	P_ALZ("ALZ", "NOTIfication for COLlection number (NOTICOL)"),
	P_AMA("AMA", "Previous request for metered reading reference number"),
	P_AMB("AMB", "Next rental agreement number"),
	P_AMC("AMC", "Reference number of a request for metered reading"),
	P_AMD("AMD", "Hastening number"),
	P_AME("AME", "Repair data request number"),
	P_AMF("AMF", "Consumption data request number"),
	P_AMG("AMG", "Profile number"),
	P_AMH("AMH", "Case number"),
	P_AMI("AMI", "Government quality assurance and control level Number"),
	P_AMJ("AMJ", "Payment plan reference"),
	P_AMK("AMK", "Replaced meter unit number"),
	P_AML("AML", "Replenishment purchase order range end number"),
	P_AMM("AMM", "Insurer assigned reference number"),
	P_AMN("AMN", "Canadian excise entry number"),
	P_AMO("AMO", "Premium rate table"),
	P_AMP("AMP", "Advise through bank's reference"),
	P_AMQ("AMQ", "US, Department of Transportation bond surety code"),
	P_AMR("AMR", "US, Food and Drug Administration establishment indicator"),
	P_AMS("AMS", "US, Federal Communications Commission (FCC) import"),
	P_AMT("AMT", "Goods and Services Tax identification number"),
	P_AMU("AMU", "Integrated logistic support cross reference number"),
	P_AMV("AMV", "Department number"),
	P_AMW("AMW", "Buyer's catalogue number"),
	P_AMX("AMX", "Financial settlement party's reference number"),
	P_AMY("AMY", "Standard's version number"),
	P_AMZ("AMZ", "Pipeline number"),
	P_ANA("ANA", "Account servicing bank's reference number"),
	P_ANB("ANB", "Completed units payment request reference"),
	P_ANC("ANC", "Payment in advance request reference"),
	P_AND("AND", "Parent file"),
	P_ANE("ANE", "Sub file"),
	P_ANF("ANF", "CAD file layer convention"),
	P_ANG("ANG", "Technical regulation"),
	P_ANH("ANH", "Plot file"),
	P_ANI("ANI", "File conversion journal"),
	P_ANJ("ANJ", "Authorization number"),
	P_ANK("ANK", "Reference number assigned by third party"),
	P_ANL("ANL", "Deposit reference number"),
	P_ANM("ANM", "Named bank's reference"),
	P_ANN("ANN", "Drawee's reference"),
	P_ANO("ANO", "Case of need party's reference"),
	P_ANP("ANP", "Collecting bank's reference"),
	P_ANQ("ANQ", "Remitting bank's reference"),
	P_ANR("ANR", "Principal's bank reference"),
	P_ANS("ANS", "Presenting bank's reference"),
	P_ANT("ANT", "Consignee's reference"),
	P_ANU("ANU", "Financial transaction reference number"),
	P_ANV("ANV", "Credit reference number"),
	P_ANW("ANW", "Receiving bank's authorization number"),
	P_ANX("ANX", "Clearing reference"),
	P_ANY("ANY", "Sending bank's reference number"),
	P_AOA("AOA", "Documentary payment reference"),
	P_AOD("AOD", "Accounting file reference"),
	P_AOE("AOE", "Sender's file reference number"),
	P_AOF("AOF", "Receiver's file reference number"),
	P_AOG("AOG", "Source document internal reference"),
	P_AOH("AOH", "Principal's reference"),
	P_AOI("AOI", "Debit reference number"),
	P_AOJ("AOJ", "Calendar"),
	P_AOK("AOK", "Work shift"),
	P_AOL("AOL", "Work breakdown structure"),
	P_AOM("AOM", "Organisation breakdown structure"),
	P_AON("AON", "Work task charge number"),
	P_AOO("AOO", "Functional work group"),
	P_AOP("AOP", "Work team"),
	P_AOQ("AOQ", "Department"),
	P_AOR("AOR", "Statement of work"),
	P_AOS("AOS", "Work package"),
	P_AOT("AOT", "Planning package"),
	P_AOU("AOU", "Cost account"),
	P_AOV("AOV", "Work order"),
	P_AOW("AOW", "Transportation Control Number (TCN)"),
	P_AOX("AOX", "Constraint notation"),
	P_AOY("AOY", "ETERMS reference"),
	P_AOZ("AOZ", "Implementation version number"),
	P_AP("AP", "Accounts receivable number"),
	P_APA("APA", "Incorporated legal reference"),
	P_APB("APB", "Payment instalment reference number"),
	P_APC("APC", "Equipment owner reference number"),
	P_APD("APD", "Cedent's claim number"),
	P_APE("APE", "Reinsurer's claim number"),
	P_APF("APF", "Price/sales catalogue response reference number"),
	P_APG("APG", "General purpose message reference number"),
	P_APH("APH", "Invoicing data sheet reference number"),
	P_API("API", "Inventory report reference number"),
	P_APJ("APJ", "Ceiling formula reference number"),
	P_APK("APK", "Price variation formula reference number"),
	P_APL("APL", "Reference to account servicing bank's message"),
	P_APM("APM", "Party sequence number"),
	P_APN("APN", "Purchaser's request reference"),
	P_APO("APO", "Contractor request reference"),
	P_APP("APP", "Accident reference number"),
	P_APQ("APQ", "Commercial account summary reference number"),
	P_APR("APR", "Contract breakdown reference"),
	P_APS("APS", "Contractor registration number"),
	P_APT("APT", "Applicable coefficient identification number"),
	P_APU("APU", "Special budget account number"),
	P_APV("APV", "Authorisation for repair reference"),
	P_APW("APW", "Manufacturer defined repair rates reference"),
	P_APX("APX", "Original submitter log number"),
	P_APY("APY", "Original submitter, parent Data Maintenance Request (DMR)"),
	P_APZ("APZ", "Original submitter, child Data Maintenance Request (DMR)"),
	P_AQA("AQA", "Entry point assessment log number"),
	P_AQB("AQB", "Entry point assessment log number, parent DMR"),
	P_AQC("AQC", "Entry point assessment log number, child DMR"),
	P_AQD("AQD", "Data structure tag"),
	P_AQE("AQE", "Central secretariat log number"),
	P_AQF("AQF", "Central secretariat log number, parent Data Maintenance"),
	P_AQG("AQG", "Central secretariat log number, child Data Maintenance"),
	P_AQH("AQH", "International assessment log number"),
	P_AQI("AQI", "International assessment log number, parent Data"),
	P_AQJ("AQJ", "International assessment log number, child Data Maintenance"),
	P_AQK("AQK", "Status report number"),
	P_AQL("AQL", "Message design group number"),
	P_AQM("AQM", "US Customs Service (USCS) entry code"),
	P_AQN("AQN", "Beginning job sequence number"),
	P_AQO("AQO", "Sender's clause number"),
	P_AQP("AQP", "Dun and Bradstreet Canada's 8 digit Standard Industrial"),
	P_AQQ("AQQ", "Activite Principale Exercee (APE) identifier"),
	P_AQR("AQR", "Dun and Bradstreet US 8 digit Standard Industrial"),
	P_AQS("AQS", "Nomenclature Activity Classification Economy (NACE)"),
	P_AQT("AQT", "Norme Activite Francaise (NAF) identifier"),
	P_AQU("AQU", "Registered contractor activity type"),
	P_AQV("AQV", "Statistic Bundes Amt (SBA) identifier"),
	P_AQW("AQW", "State or province assigned entity identification"),
	P_AQX("AQX", "Institute of Security and Future Market Development (ISFMD)"),
	P_AQY("AQY", "File identification number"),
	P_AQZ("AQZ", "Bankruptcy procedure number"),
	P_ARA("ARA", "National government business identification number"),
	P_ARB("ARB", "Prior Data Universal Number System (DUNS) number"),
	P_ARC("ARC", "Companies Registry Office (CRO) number"),
	P_ARD("ARD", "Costa Rican judicial number"),
	P_ARE("ARE", "Numero de Identificacion Tributaria (NIT)"),
	P_ARF("ARF", "Patron number"),
	P_ARG("ARG", "Registro Informacion Fiscal (RIF) number"),
	P_ARH("ARH", "Registro Unico de Contribuyente (RUC) number"),
	P_ARI("ARI", "Tokyo SHOKO Research (TSR) business identifier"),
	P_ARJ("ARJ", "Personal identity card number"),
	P_ARK("ARK", "Systeme Informatique pour le Repertoire des ENtreprises"),
	P_ARL("ARL", "Systeme Informatique pour le Repertoire des ETablissements"),
	P_ARM("ARM", "Publication issue number"),
	P_ARN("ARN", "Original filing number"),
	P_ARO("ARO", "Document page identifier"),
	P_ARP("ARP", "Public filing registration number"),
	P_ARQ("ARQ", "Regiristo Federal de Contribuyentes"),
	P_ARR("ARR", "Social security number"),
	P_ARS("ARS", "Document volume number"),
	P_ART("ART", "Book number"),
	P_ARU("ARU", "Stock exchange company identifier"),
	P_ARV("ARV", "Imputation account"),
	P_ARW("ARW", "Financial phase reference"),
	P_ARX("ARX", "Technical phase reference"),
	P_ARY("ARY", "Prior contractor registration number"),
	P_ARZ("ARZ", "Stock adjustment number"),
	P_ASA("ASA", "Dispensation reference"),
	P_ASB("ASB", "Investment reference number"),
	P_ASC("ASC", "Assuming company"),
	P_ASD("ASD", "Budget chapter"),
	P_ASE("ASE", "Duty free products security number"),
	P_ASF("ASF", "Duty free products receipt authorisation number"),
	P_ASG("ASG", "Party information message reference"),
	P_ASH("ASH", "Formal statement reference"),
	P_ASI("ASI", "Proof of delivery reference number"),
	P_ASJ("ASJ", "Supplier's credit claim reference number"),
	P_ASK("ASK", "Picture of actual product"),
	P_ASL("ASL", "Picture of a generic product"),
	P_ASM("ASM", "Trading partner identification number"),
	P_ASN("ASN", "Prior trading partner identification number"),
	P_ASO("ASO", "Password"),
	P_ASP("ASP", "Formal report number"),
	P_ASQ("ASQ", "Fund account number"),
	P_ASR("ASR", "Safe custody number"),
	P_ASS("ASS", "Master account number"),
	P_AST("AST", "Group reference number"),
	P_ASU("ASU", "Accounting transmission number"),
	P_ASV("ASV", "Product data file number"),
	P_ASW("ASW", "Cadastro Geral do Contribuinte (CGC)"),
	P_ASX("ASX", "Foreign resident identification number"),
	P_ASY("ASY", "CD-ROM"),
	P_ASZ("ASZ", "Physical medium"),
	P_ATA("ATA", "Financial cancellation reference number"),
	P_ATB("ATB", "Purchase for export Customs agreement number"),
	P_ATC("ATC", "Judgment number"),
	P_ATD("ATD", "Secretariat number"),
	P_ATE("ATE", "Previous banking status message reference"),
	P_ATF("ATF", "Last received banking status message reference"),
	P_ATG("ATG", "Bank's documentary procedure reference"),
	P_ATH("ATH", "Customer's documentary procedure reference"),
	P_ATI("ATI", "Safe deposit box number"),
	P_ATJ("ATJ", "Receiving Bankgiro number"),
	P_ATK("ATK", "Sending Bankgiro number"),
	P_ATL("ATL", "Bankgiro reference"),
	P_ATM("ATM", "Guarantee number"),
	P_ATN("ATN", "Collection instrument number"),
	P_ATO("ATO", "Converted Postgiro number"),
	P_ATP("ATP", "Cost centre alignment number"),
	P_ATQ("ATQ", "Kamer Van Koophandel (KVK) number"),
	P_ATR("ATR", "Institut Belgo-Luxembourgeois de Codification (IBLC) number"),
	P_ATS("ATS", "External object reference"),
	P_ATT("ATT", "Exceptional transport authorisation number"),
	P_ATU("ATU", "Clave Unica de Identificacion Tributaria (CUIT)"),
	P_ATV("ATV", "Registro Unico Tributario (RUT)"),
	P_ATW("ATW", "Flat rack container bundle identification number"),
	P_ATX("ATX", "Transport equipment acceptance order reference"),
	P_ATY("ATY", "Transport equipment release order reference"),
	P_ATZ("ATZ", "Ship's stay reference number"),
	P_AU("AU", "Authorization to meet competition number"),
	P_AUA("AUA", "Place of positioning reference"),
	P_AUB("AUB", "Party reference"),
	P_AUC("AUC", "Issued prescription identification"),
	P_AUD("AUD", "Collection reference"),
	P_AUE("AUE", "Travel service"),
	P_AUF("AUF", "Consignment stock contract"),
	P_AUG("AUG", "Importer's letter of credit reference"),
	P_AUH("AUH", "Performed prescription identification"),
	P_AUI("AUI", "Image reference"),
	P_AUJ("AUJ", "Proposed purchase order reference number"),
	P_AUK("AUK", "Application for financial support reference number"),
	P_AUL("AUL", "Manufacturing quality agreement number"),
	P_AUM("AUM", "Software editor reference"),
	P_AUN("AUN", "Software reference"),
	P_AUO("AUO", "Software quality reference"),
	P_AUP("AUP", "Consolidated orders' reference"),
	P_AUQ("AUQ", "Customs binding ruling number"),
	P_AUR("AUR", "Customs non-binding ruling number"),
	P_AUS("AUS", "Delivery route reference"),
	P_AUT("AUT", "Net area supplier reference"),
	P_AUU("AUU", "Time series reference"),
	P_AUV("AUV", "Connecting point to central grid"),
	P_AUW("AUW", "Marketing plan identification number (MPIN)"),
	P_AUX("AUX", "Entity reference number, previous"),
	P_AUY("AUY", "International Standard Industrial Classification (ISIC)"),
	P_AUZ("AUZ", "Customs pre-approval ruling number"),
	P_AV("AV", "Account payable number"),
	P_AVA("AVA", "First financial institution's transaction reference"),
	P_AVB("AVB", "Product characteristics directory"),
	P_AVC("AVC", "Supplier's customer reference number"),
	P_AVD("AVD", "Inventory report request number"),
	P_AVE("AVE", "Metering point"),
	P_AVF("AVF", "Passenger reservation number"),
	P_AVG("AVG", "Slaughterhouse approval number"),
	P_AVH("AVH", "Meat cutting plant approval number"),
	P_AVI("AVI", "Customer travel service identifier"),
	P_AVJ("AVJ", "Export control classification number"),
	P_AVK("AVK", "Broker reference 3"),
	P_AVL("AVL", "Consignment information"),
	P_AVM("AVM", "Goods item information"),
	P_AVN("AVN", "Dangerous Goods information"),
	P_AVO("AVO", "Pilotage services exemption number"),
	P_AVP("AVP", "Person registration number"),
	P_AVQ("AVQ", "Place of packing approval number"),
	P_AVR("AVR", "Original Mandate Reference"),
	P_AVS("AVS", "Mandate Reference"),
	P_AVT("AVT", "Reservation station indentifier"),
	P_AVU("AVU", "Unique goods shipment identifier"),
	P_AVV("AVV", "Framework Agreement Number"),
	P_AVW("AVW", "Hash value"),
	P_AVX("AVX", "Movement reference number"),
	P_AVY("AVY", "Economic Operators Registration and Identification Number"),
	P_AVZ("AVZ", "Local Reference Number"),
	P_AWA("AWA", "Rate code number"),
	P_AWB("AWB", "Air waybill number"),
	P_AWC("AWC", "Documentary credit amendment number"),
	P_AWD("AWD", "Advising bank's reference"),
	P_AWE("AWE", "Cost centre"),
	P_AWF("AWF", "Work item quantity determination"),
	P_AWG("AWG", "Internal data process number"),
	P_AWH("AWH", "Category of work reference"),
	P_AWI("AWI", "Policy form number"),
	P_AWJ("AWJ", "Net area"),
	P_AWK("AWK", "Service provider"),
	P_AWL("AWL", "Error position"),
	P_AWM("AWM", "Service category reference"),
	P_AWN("AWN", "Connected location"),
	P_AWO("AWO", "Related party"),
	P_AWP("AWP", "Latest accounting entry record reference"),
	P_AWQ("AWQ", "Accounting entry"),
	P_AWR("AWR", "Document reference, original"),
	P_AWS("AWS", "Hygienic Certificate number, national"),
	P_AWT("AWT", "Administrative Reference Code"),
	P_AWU("AWU", "Pick-up sheet number"),
	P_AWV("AWV", "Phone number"),
	P_AWW("AWW", "Buyer's fund number"),
	P_AWX("AWX", "Company trading account number"),
	P_AWY("AWY", "Reserved goods identifier"),
	P_AWZ("AWZ", "Handling and movement reference number"),
	P_AXA("AXA", "Instruction to despatch reference number"),
	P_AXB("AXB", "Instruction for returns number"),
	P_AXC("AXC", "Metered services consumption report number"),
	P_AXD("AXD", "Order status enquiry number"),
	P_AXE("AXE", "Firm booking reference number"),
	P_AXF("AXF", "Product inquiry number"),
	P_AXG("AXG", "Split delivery number"),
	P_AXH("AXH", "Service relation number"),
	P_AXI("AXI", "Serial shipping container code"),
	P_AXJ("AXJ", "Test specification number"),
	P_AXK("AXK", "Transport status report number"),
	P_AXL("AXL", "Tooling contract number"),
	P_AXM("AXM", "Formula reference number"),
	P_AXN("AXN", "Pre-agreement number"),
	P_AXO("AXO", "Product certification number"),
	P_AXP("AXP", "Consignment contract number"),
	P_AXQ("AXQ", "Product specification reference number"),
	P_AXR("AXR", "Payroll deduction advice reference"),
	P_AXS("AXS", "TRACES party identification"),
	P_BA("BA", "Beginning meter reading actual"),
	P_BC("BC", "Buyer's contract number"),
	P_BD("BD", "Bid number"),
	P_BE("BE", "Beginning meter reading estimated"),
	P_BH("BH", "House bill of lading number"),
	P_BM("BM", "Bill of lading number"),
	P_BN("BN", "Consignment identifier, carrier assigned"),
	P_BO("BO", "Blanket order number"),
	P_BR("BR", "Broker or sales office number"),
	P_BT("BT", "Batch number/lot number"),
	P_BTP("BTP", "Battery and accumulator producer registration number"),
	P_BW("BW", "Blended with number"),
	P_CAS("CAS", "IATA Cargo Agent CASS Address number"),
	P_CAT("CAT", "Matching of entries, balanced"),
	P_CAU("CAU", "Entry flagging"),
	P_CAV("CAV", "Matching of entries, unbalanced"),
	P_CAW("CAW", "Document reference, internal"),
	P_CAX("CAX", "European Value Added Tax identification"),
	P_CAY("CAY", "Cost accounting document"),
	P_CAZ("CAZ", "Grid operator's customer reference number"),
	P_CBA("CBA", "Ticket control number"),
	P_CBB("CBB", "Order shipment grouping reference"),
	P_CD("CD", "Credit note number"),
	P_CEC("CEC", "Ceding company"),
	P_CED("CED", "Debit letter number"),
	P_CFE("CFE", "Consignee's further order"),
	P_CFF("CFF", "Animal farm licence number"),
	P_CFO("CFO", "Consignor's further order"),
	P_CG("CG", "Consignee's order number"),
	P_CH("CH", "Customer catalogue number"),
	P_CK("CK", "Cheque number"),
	P_CKN("CKN", "Checking number"),
	P_CM("CM", "Credit memo number"),
	P_CMR("CMR", "Road consignment note number"),
	P_CN("CN", "Carrier's reference number"),
	P_CNO("CNO", "Charges note document attachment indicator"),
	P_COF("COF", "Call off order number"),
	P_CP("CP", "Condition of purchase document number"),
	P_CR("CR", "Customer reference number"),
	P_CRN("CRN", "Transport means journey identifier"),
	P_CS("CS", "Condition of sale document number"),
	P_CST("CST", "Team assignment number"),
	P_CT("CT", "Contract number"),
	P_CU("CU", "Consignment identifier, consignor assigned"),
	P_CV("CV", "Container operators reference number"),
	P_CW("CW", "Package number"),
	P_CZ("CZ", "Cooperation contract number"),
	P_DA("DA", "Deferment approval number"),
	P_DAN("DAN", "Debit account number"),
	P_DB("DB", "Buyer's debtor number"),
	P_DI("DI", "Distributor invoice number"),
	P_DL("DL", "Debit note number"),
	P_DM("DM", "Document identifier"),
	P_DQ("DQ", "Delivery note number"),
	P_DR("DR", "Dock receipt number"),
	P_EA("EA", "Ending meter reading actual"),
	P_EB("EB", "Embargo permit number"),
	P_ED("ED", "Export declaration"),
	P_EE("EE", "Ending meter reading estimated"),
	P_EEP("EEP", "Electrical and electronic equipment producer registration"),
	P_EI("EI", "Employer's identification number"),
	P_EN("EN", "Embargo number"),
	P_EQ("EQ", "Equipment number"),
	P_ER("ER", "Container/equipment receipt number"),
	P_ERN("ERN", "Exporter's reference number"),
	P_ET("ET", "Excess transportation number"),
	P_EX("EX", "Export permit identifier"),
	P_FC("FC", "Fiscal number"),
	P_FF("FF", "Consignment identifier, freight forwarder assigned"),
	P_FI("FI", "File line identifier"),
	P_FLW("FLW", "Flow reference number"),
	P_FN("FN", "Freight bill number"),
	P_FO("FO", "Foreign exchange"),
	P_FS("FS", "Final sequence number"),
	P_FT("FT", "Free zone identifier"),
	P_FV("FV", "File version number"),
	P_FX("FX", "Foreign exchange contract number"),
	P_GA("GA", "Standard's number"),
	P_GC("GC", "Government contract number"),
	P_GD("GD", "Standard's code number"),
	P_GDN("GDN", "General declaration number"),
	P_GN("GN", "Government reference number"),
	P_HS("HS", "Harmonised system number"),
	P_HWB("HWB", "House waybill number"),
	P_IA("IA", "Internal vendor number"),
	P_IB("IB", "In bond number"),
	P_ICA("ICA", "IATA cargo agent code number"),
	P_ICE("ICE", "Insurance certificate reference number"),
	P_ICO("ICO", "Insurance contract reference number"),
	P_II("II", "Initial sample inspection report number"),
	P_IL("IL", "Internal order number"),
	P_INB("INB", "Intermediary broker"),
	P_INN("INN", "Interchange number new"),
	P_INO("INO", "Interchange number old"),
	P_IP("IP", "Import permit identifier"),
	P_IS("IS", "Invoice number suffix"),
	P_IT("IT", "Internal customer number"),
	P_IV("IV", "Invoice document identifier"),
	P_JB("JB", "Job number"),
	P_JE("JE", "Ending job sequence number"),
	P_LA("LA", "Shipping label serial number"),
	P_LAN("LAN", "Loading authorisation identifier"),
	P_LAR("LAR", "Lower number in range"),
	P_LB("LB", "Lockbox"),
	P_LC("LC", "Letter of credit number"),
	P_LI("LI", "Document line identifier"),
	P_LO("LO", "Load planning number"),
	P_LRC("LRC", "Reservation office identifier"),
	P_LS("LS", "Bar coded label serial number"),
	P_MA("MA", "Ship notice/manifest number"),
	P_MB("MB", "Master bill of lading number"),
	P_MF("MF", "Manufacturer's part number"),
	P_MG("MG", "Meter unit number"),
	P_MH("MH", "Manufacturing order number"),
	P_MR("MR", "Message recipient"),
	P_MRN("MRN", "Mailing reference number"),
	P_MS("MS", "Message sender"),
	P_MSS("MSS", "Manufacturer's material safety data sheet number"),
	P_MWB("MWB", "Master air waybill number"),
	P_NA("NA", "North American hazardous goods classification number"),
	P_NF("NF", "Nota Fiscal"),
	P_OH("OH", "Current invoice number"),
	P_OI("OI", "Previous invoice number"),
	P_ON("ON", "Order document identifier, buyer assigned"),
	P_OP("OP", "Original purchase order"),
	P_OR("OR", "General order number"),
	P_PB("PB", "Payer's financial institution account number"),
	P_PC("PC", "Production code"),
	P_PD("PD", "Promotion deal number"),
	P_PE("PE", "Plant number"),
	P_PF("PF", "Prime contractor contract number"),
	P_PI("PI", "Price list version number"),
	P_PK("PK", "Packing list number"),
	P_PL("PL", "Price list number"),
	P_POR("POR", "Purchase order response number"),
	P_PP("PP", "Purchase order change number"),
	P_PQ("PQ", "Payment reference"),
	P_PR("PR", "Price quote number"),
	P_PS("PS", "Purchase order number suffix"),
	P_PW("PW", "Prior purchase order number"),
	P_PY("PY", "Payee's financial institution account number"),
	P_RA("RA", "Remittance advice number"),
	P_RC("RC", "Rail/road routing code"),
	P_RCN("RCN", "Railway consignment note number"),
	P_RE("RE", "Release number"),
	P_REN("REN", "Consignment receipt identifier"),
	P_RF("RF", "Export reference number"),
	P_RR("RR", "Payer's financial institution transit routing No.(ACH transfers)"),
	P_RT("RT", "Payee's financial institution transit routing No."),
	P_SA("SA", "Sales person number"),
	P_SB("SB", "Sales region number"),
	P_SD("SD", "Sales department number"),
	P_SE("SE", "Serial number"),
	P_SEA("SEA", "Allocated seat"),
	P_SF("SF", "Ship from"),
	P_SH("SH", "Previous highest schedule number"),
	P_SI("SI", "SID (Shipper's identifying number for shipment)"),
	P_SM("SM", "Sales office number"),
	P_SN("SN", "Transport equipment seal identifier"),
	P_SP("SP", "Scan line"),
	P_SQ("SQ", "Equipment sequence number"),
	P_SRN("SRN", "Shipment reference number"),
	P_SS("SS", "Sellers reference number"),
	P_STA("STA", "Station reference number"),
	P_SW("SW", "Swap order number"),
	P_SZ("SZ", "Specification number"),
	P_TB("TB", "Trucker's bill of lading"),
	P_TCR("TCR", "Terminal operator's consignment reference"),
	P_TE("TE", "Telex message number"),
	P_TF("TF", "Transfer number"),
	P_TI("TI", "TIR carnet number"),
	P_TIN("TIN", "Transport instruction number"),
	P_TL("TL", "Tax exemption licence number"),
	P_TN("TN", "Transaction reference number"),
	P_TP("TP", "Test report number"),
	P_UAR("UAR", "Upper number of range"),
	P_UC("UC", "Ultimate customer's reference number"),
	P_UCN("UCN", "Unique consignment reference number"),
	P_UN("UN", "United Nations Dangerous Goods identifier"),
	P_UO("UO", "Ultimate customer's order number"),
	P_URI("URI", "Uniform Resource Identifier"),
	P_VA("VA", "VAT registration number"),
	P_VC("VC", "Vendor contract number"),
	P_VGR("VGR", "Transport equipment gross mass verification reference"),
	P_VM("VM", "Vessel identifier"),
	P_VN("VN", "Order number (vendor)"),
	P_VON("VON", "Voyage number"),
	P_VOR("VOR", "Transport equipment gross mass verification order reference"),
	P_VP("VP", "Vendor product number"),
	P_VR("VR", "Vendor ID number"),
	P_VS("VS", "Vendor order number suffix"),
	P_VT("VT", "Motor vehicle identification number"),
	P_VV("VV", "Voucher number"),
	P_WE("WE", "Warehouse entry number"),
	P_WM("WM", "Weight agreement number"),
	P_WN("WN", "Well number"),
	P_WR("WR", "Warehouse receipt number"),
	P_WS("WS", "Warehouse storage location number"),
	P_WY("WY", "Rail waybill number"),
	P_XA("XA", "Company/place registration number"),
	P_XC("XC", "Cargo control number"),
	P_XP("XP", "Previous cargo control number"),
	P_ZZZ("ZZZ", "Mutually defined reference number");

	private final String code;
	private final String fullName;

	Uncl1153(String code, String fullName) {
		this.code = code;
		this.fullName = fullName;
	}

	public String getCode(){
		return code;
	}

	public String getFullName(){
		return fullName;
	}
}
