package sxr.model.codes;

public enum Iso3166 {
	P_AD("AD", "Andorra"),
	P_AE("AE", "United Arab Emirates"),
	P_AF("AF", "Afghanistan"),
	P_AG("AG", "Antigua and Barbuda"),
	P_AI("AI", "Anguilla"),
	P_AL("AL", "Albania"),
	P_AM("AM", "Armenia"),
	P_AO("AO", "Angola"),
	P_AQ("AQ", "Antarctica"),
	P_AR("AR", "Argentina"),
	P_AS("AS", "American Samoa"),
	P_AT("AT", "Austria"),
	P_AU("AU", "Australia"),
	P_AW("AW", "Aruba"),
	P_AX("AX", "Åland Islands"),
	P_AZ("AZ", "Azerbaijan"),
	P_BA("BA", "Bosnia and Herzegovina"),
	P_BB("BB", "Barbados"),
	P_BD("BD", "Bangladesh"),
	P_BE("BE", "Belgium"),
	P_BF("BF", "Burkina Faso"),
	P_BG("BG", "Bulgaria"),
	P_BH("BH", "Bahrain"),
	P_BI("BI", "Burundi"),
	P_BJ("BJ", "Benin"),
	P_BL("BL", "Saint Barthélemy"),
	P_BM("BM", "Bermuda"),
	P_BN("BN", "Brunei Darussalam"),
	P_BO("BO", "Bolivia, Plurinational State of"),
	P_BQ("BQ", "Bonaire, Sint Eustatius and Saba"),
	P_BR("BR", "Brazil"),
	P_BS("BS", "Bahamas"),
	P_BT("BT", "Bhutan"),
	P_BV("BV", "Bouvet Island"),
	P_BW("BW", "Botswana"),
	P_BY("BY", "Belarus"),
	P_BZ("BZ", "Belize"),
	P_CA("CA", "Canada"),
	P_CC("CC", "Cocos (Keeling) Islands"),
	P_CD("CD", "Congo, the Democratic Republic of the"),
	P_CF("CF", "Central African Republic"),
	P_CG("CG", "Congo"),
	P_CH("CH", "Switzerland"),
	P_CI("CI", "Côte d'Ivoire"),
	P_CK("CK", "Cook Islands"),
	P_CL("CL", "Chile"),
	P_CM("CM", "Cameroon"),
	P_CN("CN", "China"),
	P_CO("CO", "Colombia"),
	P_CR("CR", "Costa Rica"),
	P_CU("CU", "Cuba"),
	P_CV("CV", "Cabo Verde"),
	P_CW("CW", "Curaçao"),
	P_CX("CX", "Christmas Island"),
	P_CY("CY", "Cyprus"),
	P_CZ("CZ", "Czechia"),
	P_DE("DE", "Germany"),
	P_DJ("DJ", "Djibouti"),
	P_DK("DK", "Denmark"),
	P_DM("DM", "Dominica"),
	P_DO("DO", "Dominican Republic"),
	P_DZ("DZ", "Algeria"),
	P_EC("EC", "Ecuador"),
	P_EE("EE", "Estonia"),
	P_EG("EG", "Egypt"),
	P_EH("EH", "Western Sahara"),
	P_ER("ER", "Eritrea"),
	P_ES("ES", "Spain"),
	P_ET("ET", "Ethiopia"),
	P_FI("FI", "Finland"),
	P_FJ("FJ", "Fiji"),
	P_FK("FK", "Falkland Islands (Malvinas)"),
	P_FM("FM", "Micronesia, Federated States of"),
	P_FO("FO", "Faroe Islands"),
	P_FR("FR", "France"),
	P_GA("GA", "Gabon"),
	P_GB("GB", "United Kingdom of Great Britain and Northern Ireland"),
	P_GD("GD", "Grenada"),
	P_GE("GE", "Georgia"),
	P_GF("GF", "French Guiana"),
	P_GG("GG", "Guernsey"),
	P_GH("GH", "Ghana"),
	P_GI("GI", "Gibraltar"),
	P_GL("GL", "Greenland"),
	P_GM("GM", "Gambia"),
	P_GN("GN", "Guinea"),
	P_GP("GP", "Guadeloupe"),
	P_GQ("GQ", "Equatorial Guinea"),
	P_GR("GR", "Greece"),
	P_GS("GS", "South Georgia and the South Sandwich Islands"),
	P_GT("GT", "Guatemala"),
	P_GU("GU", "Guam"),
	P_GW("GW", "Guinea-Bissau"),
	P_GY("GY", "Guyana"),
	P_HK("HK", "Hong Kong"),
	P_HM("HM", "Heard Island and McDonald Islands"),
	P_HN("HN", "Honduras"),
	P_HR("HR", "Croatia"),
	P_HT("HT", "Haiti"),
	P_HU("HU", "Hungary"),
	P_ID("ID", "Indonesia"),
	P_IE("IE", "Ireland"),
	P_IL("IL", "Israel"),
	P_IM("IM", "Isle of Man"),
	P_IN("IN", "India"),
	P_IO("IO", "British Indian Ocean Territory"),
	P_IQ("IQ", "Iraq"),
	P_IR("IR", "Iran, Islamic Republic of"),
	P_IS("IS", "Iceland"),
	P_IT("IT", "Italy"),
	P_JE("JE", "Jersey"),
	P_JM("JM", "Jamaica"),
	P_JO("JO", "Jordan"),
	P_JP("JP", "Japan"),
	P_KE("KE", "Kenya"),
	P_KG("KG", "Kyrgyzstan"),
	P_KH("KH", "Cambodia"),
	P_KI("KI", "Kiribati"),
	P_KM("KM", "Comoros"),
	P_KN("KN", "Saint Kitts and Nevis"),
	P_KP("KP", "Korea, Democratic People's Republic of"),
	P_KR("KR", "Korea, Republic of"),
	P_KW("KW", "Kuwait"),
	P_KY("KY", "Cayman Islands"),
	P_KZ("KZ", "Kazakhstan"),
	P_LA("LA", "Lao People's Democratic Republic"),
	P_LB("LB", "Lebanon"),
	P_LC("LC", "Saint Lucia"),
	P_LI("LI", "Liechtenstein"),
	P_LK("LK", "Sri Lanka"),
	P_LR("LR", "Liberia"),
	P_LS("LS", "Lesotho"),
	P_LT("LT", "Lithuania"),
	P_LU("LU", "Luxembourg"),
	P_LV("LV", "Latvia"),
	P_LY("LY", "Libya"),
	P_MA("MA", "Morocco"),
	P_MC("MC", "Monaco"),
	P_MD("MD", "Moldova, Republic of"),
	P_ME("ME", "Montenegro"),
	P_MF("MF", "Saint Martin (French part)"),
	P_MG("MG", "Madagascar"),
	P_MH("MH", "Marshall Islands"),
	P_MK("MK", "Macedonia, the former Yugoslav Republic of"),
	P_ML("ML", "Mali"),
	P_MM("MM", "Myanmar"),
	P_MN("MN", "Mongolia"),
	P_MO("MO", "Macao"),
	P_MP("MP", "Northern Mariana Islands"),
	P_MQ("MQ", "Martinique"),
	P_MR("MR", "Mauritania"),
	P_MS("MS", "Montserrat"),
	P_MT("MT", "Malta"),
	P_MU("MU", "Mauritius"),
	P_MV("MV", "Maldives"),
	P_MW("MW", "Malawi"),
	P_MX("MX", "Mexico"),
	P_MY("MY", "Malaysia"),
	P_MZ("MZ", "Mozambique"),
	P_NA("NA", "Namibia"),
	P_NC("NC", "New Caledonia"),
	P_NE("NE", "Niger"),
	P_NF("NF", "Norfolk Island"),
	P_NG("NG", "Nigeria"),
	P_NI("NI", "Nicaragua"),
	P_NL("NL", "Netherlands"),
	P_NO("NO", "Norway"),
	P_NP("NP", "Nepal"),
	P_NR("NR", "Nauru"),
	P_NU("NU", "Niue"),
	P_NZ("NZ", "New Zealand"),
	P_OM("OM", "Oman"),
	P_PA("PA", "Panama"),
	P_PE("PE", "Peru"),
	P_PF("PF", "French Polynesia"),
	P_PG("PG", "Papua New Guinea"),
	P_PH("PH", "Philippines"),
	P_PK("PK", "Pakistan"),
	P_PL("PL", "Poland"),
	P_PM("PM", "Saint Pierre and Miquelon"),
	P_PN("PN", "Pitcairn"),
	P_PR("PR", "Puerto Rico"),
	P_PS("PS", "Palestine, State of"),
	P_PT("PT", "Portugal"),
	P_PW("PW", "Palau"),
	P_PY("PY", "Paraguay"),
	P_QA("QA", "Qatar"),
	P_RE("RE", "Réunion"),
	P_RO("RO", "Romania"),
	P_RS("RS", "Serbia"),
	P_RU("RU", "Russian Federation"),
	P_RW("RW", "Rwanda"),
	P_SA("SA", "Saudi Arabia"),
	P_SB("SB", "Solomon Islands"),
	P_SC("SC", "Seychelles"),
	P_SD("SD", "Sudan"),
	P_SE("SE", "Sweden"),
	P_SG("SG", "Singapore"),
	P_SH("SH", "Saint Helena, Ascension and Tristan da Cunha"),
	P_SI("SI", "Slovenia"),
	P_SJ("SJ", "Svalbard and Jan Mayen"),
	P_SK("SK", "Slovakia"),
	P_SL("SL", "Sierra Leone"),
	P_SM("SM", "San Marino"),
	P_SN("SN", "Senegal"),
	P_SO("SO", "Somalia"),
	P_SR("SR", "Suriname"),
	P_SS("SS", "South Sudan"),
	P_ST("ST", "Sao Tome and Principe"),
	P_SV("SV", "El Salvador"),
	P_SX("SX", "Sint Maarten (Dutch part)"),
	P_SY("SY", "Syrian Arab Republic"),
	P_SZ("SZ", "Swaziland"),
	P_TC("TC", "Turks and Caicos Islands"),
	P_TD("TD", "Chad"),
	P_TF("TF", "French Southern Territories"),
	P_TG("TG", "Togo"),
	P_TH("TH", "Thailand"),
	P_TJ("TJ", "Tajikistan"),
	P_TK("TK", "Tokelau"),
	P_TL("TL", "Timor-Leste"),
	P_TM("TM", "Turkmenistan"),
	P_TN("TN", "Tunisia"),
	P_TO("TO", "Tonga"),
	P_TR("TR", "Turkey"),
	P_TT("TT", "Trinidad and Tobago"),
	P_TV("TV", "Tuvalu"),
	P_TW("TW", "Taiwan, Province of China"),
	P_TZ("TZ", "Tanzania, United Republic of"),
	P_UA("UA", "Ukraine"),
	P_UG("UG", "Uganda"),
	P_UM("UM", "United States Minor Outlying Islands"),
	P_US("US", "United States of America"),
	P_UY("UY", "Uruguay"),
	P_UZ("UZ", "Uzbekistan"),
	P_VA("VA", "Holy See"),
	P_VC("VC", "Saint Vincent and the Grenadines"),
	P_VE("VE", "Venezuela, Bolivarian Republic of"),
	P_VG("VG", "Virgin Islands, British"),
	P_VI("VI", "Virgin Islands, U.S."),
	P_VN("VN", "Viet Nam"),
	P_VU("VU", "Vanuatu"),
	P_WF("WF", "Wallis and Futuna"),
	P_WS("WS", "Samoa"),
	P_YE("YE", "Yemen"),
	P_YT("YT", "Mayotte"),
	P_ZA("ZA", "South Africa"),
	P_ZM("ZM", "Zambia"),
	P_ZW("ZW", "Zimbabwe"),
	P_1A("1A", "Kosovo"),
	P_XI("XI", "United Kingdom (Northern Ireland)");

	private final String code;
	private final String fullName;

	Iso3166(String code, String fullName) {
		this.code = code;
		this.fullName = fullName;
	}

	public String getCode(){
		return code;
	}

	public String getFullName(){
		return fullName;
	}
}
