package sxr.model.codes;

public enum Uncl7161 {
	P_AA("AA", "Advertising"),
	P_AAA("AAA", "Telecommunication"),
	P_AAC("AAC", "Technical modification"),
	P_AAD("AAD", "Job-order production"),
	P_AAE("AAE", "Outlays"),
	P_AAF("AAF", "Off-premises"),
	P_AAH("AAH", "Additional processing"),
	P_AAI("AAI", "Attesting"),
	P_AAS("AAS", "Acceptance"),
	P_AAT("AAT", "Rush delivery"),
	P_AAV("AAV", "Special construction"),
	P_AAY("AAY", "Airport facilities"),
	P_AAZ("AAZ", "Concession"),
	P_ABA("ABA", "Compulsory storage"),
	P_ABB("ABB", "Fuel removal"),
	P_ABC("ABC", "Into plane"),
	P_ABD("ABD", "Overtime"),
	P_ABF("ABF", "Tooling"),
	P_ABK("ABK", "Miscellaneous"),
	P_ABL("ABL", "Additional packaging"),
	P_ABN("ABN", "Dunnage"),
	P_ABR("ABR", "Containerisation"),
	P_ABS("ABS", "Carton packing"),
	P_ABT("ABT", "Hessian wrapped"),
	P_ABU("ABU", "Polyethylene wrap packing"),
	P_ACF("ACF", "Miscellaneous treatment"),
	P_ACG("ACG", "Enamelling treatment"),
	P_ACH("ACH", "Heat treatment"),
	P_ACI("ACI", "Plating treatment"),
	P_ACJ("ACJ", "Painting"),
	P_ACK("ACK", "Polishing"),
	P_ACL("ACL", "Priming"),
	P_ACM("ACM", "Preservation treatment"),
	P_ACS("ACS", "Fitting"),
	P_ADC("ADC", "Consolidation"),
	P_ADE("ADE", "Bill of lading"),
	P_ADJ("ADJ", "Airbag"),
	P_ADK("ADK", "Transfer"),
	P_ADL("ADL", "Slipsheet"),
	P_ADM("ADM", "Binding"),
	P_ADN("ADN", "Repair or replacement of broken returnable package"),
	P_ADO("ADO", "Efficient logistics"),
	P_ADP("ADP", "Merchandising"),
	P_ADQ("ADQ", "Product mix"),
	P_ADR("ADR", "Other services"),
	P_ADT("ADT", "Pick-up"),
	P_ADW("ADW", "Chronic illness"),
	P_ADY("ADY", "New product introduction"),
	P_ADZ("ADZ", "Direct delivery"),
	P_AEA("AEA", "Diversion"),
	P_AEB("AEB", "Disconnect"),
	P_AEC("AEC", "Distribution"),
	P_AED("AED", "Handling of hazardous cargo"),
	P_AEF("AEF", "Rents and leases"),
	P_AEH("AEH", "Location differential"),
	P_AEI("AEI", "Aircraft refueling"),
	P_AEJ("AEJ", "Fuel shipped into storage"),
	P_AEK("AEK", "Cash on delivery"),
	P_AEL("AEL", "Small order processing service"),
	P_AEM("AEM", "Clerical or administrative services"),
	P_AEN("AEN", "Guarantee"),
	P_AEO("AEO", "Collection and recycling"),
	P_AEP("AEP", "Copyright fee collection"),
	P_AES("AES", "Veterinary inspection service"),
	P_AET("AET", "Pensioner service"),
	P_AEU("AEU", "Medicine free pass holder"),
	P_AEV("AEV", "Environmental protection service"),
	P_AEW("AEW", "Environmental clean-up service"),
	P_AEX("AEX", "National cheque processing service outside account area"),
	P_AEY("AEY", "National payment service outside account area"),
	P_AEZ("AEZ", "National payment service within account area"),
	P_AJ("AJ", "Adjustments"),
	P_AU("AU", "Authentication"),
	P_CA("CA", "Cataloguing"),
	P_CAB("CAB", "Cartage"),
	P_CAD("CAD", "Certification"),
	P_CAE("CAE", "Certificate of conformance"),
	P_CAF("CAF", "Certificate of origin"),
	P_CAI("CAI", "Cutting"),
	P_CAJ("CAJ", "Consular service"),
	P_CAK("CAK", "Customer collection"),
	P_CAL("CAL", "Payroll payment service"),
	P_CAM("CAM", "Cash transportation"),
	P_CAN("CAN", "Home banking service"),
	P_CAO("CAO", "Bilateral agreement service"),
	P_CAP("CAP", "Insurance brokerage service"),
	P_CAQ("CAQ", "Cheque generation"),
	P_CAR("CAR", "Preferential merchandising location"),
	P_CAS("CAS", "Crane"),
	P_CAT("CAT", "Special colour service"),
	P_CAU("CAU", "Sorting"),
	P_CAV("CAV", "Battery collection and recycling"),
	P_CAW("CAW", "Product take back fee"),
	P_CAX("CAX", "Quality control released"),
	P_CAY("CAY", "Quality control held"),
	P_CAZ("CAZ", "Quality control embargo"),
	P_CD("CD", "Car loading"),
	P_CG("CG", "Cleaning"),
	P_CS("CS", "Cigarette stamping"),
	P_CT("CT", "Count and recount"),
	P_DAB("DAB", "Layout/design"),
	P_DAC("DAC", "Assortment allowance"),
	P_DAD("DAD", "Driver assigned unloading"),
	P_DAF("DAF", "Debtor bound"),
	P_DAG("DAG", "Dealer allowance"),
	P_DAH("DAH", "Allowance transferable to the consumer"),
	P_DAI("DAI", "Growth of business"),
	P_DAJ("DAJ", "Introduction allowance"),
	P_DAK("DAK", "Multi-buy promotion"),
	P_DAL("DAL", "Partnership"),
	P_DAM("DAM", "Return handling"),
	P_DAN("DAN", "Minimum order not fulfilled charge"),
	P_DAO("DAO", "Point of sales threshold allowance"),
	P_DAP("DAP", "Wholesaling discount"),
	P_DAQ("DAQ", "Documentary credits transfer commission"),
	P_DL("DL", "Delivery"),
	P_EG("EG", "Engraving"),
	P_EP("EP", "Expediting"),
	P_ER("ER", "Exchange rate guarantee"),
	P_FAA("FAA", "Fabrication"),
	P_FAB("FAB", "Freight equalization"),
	P_FAC("FAC", "Freight extraordinary handling"),
	P_FC("FC", "Freight service"),
	P_FH("FH", "Filling/handling"),
	P_FI("FI", "Financing"),
	P_GAA("GAA", "Grinding"),
	P_HAA("HAA", "Hose"),
	P_HD("HD", "Handling"),
	P_HH("HH", "Hoisting and hauling"),
	P_IAA("IAA", "Installation"),
	P_IAB("IAB", "Installation and warranty"),
	P_ID("ID", "Inside delivery"),
	P_IF("IF", "Inspection"),
	P_IR("IR", "Installation and training"),
	P_IS("IS", "Invoicing"),
	P_KO("KO", "Koshering"),
	P_L1("L1", "Carrier count"),
	P_LA("LA", "Labelling"),
	P_LAA("LAA", "Labour"),
	P_LAB("LAB", "Repair and return"),
	P_LF("LF", "Legalisation"),
	P_MAE("MAE", "Mounting"),
	P_MI("MI", "Mail invoice"),
	P_ML("ML", "Mail invoice to each location"),
	P_NAA("NAA", "Non-returnable containers"),
	P_OA("OA", "Outside cable connectors"),
	P_PA("PA", "Invoice with shipment"),
	P_PAA("PAA", "Phosphatizing (steel treatment)"),
	P_PC("PC", "Packing"),
	P_PL("PL", "Palletizing"),
	P_PRV("PRV", "Price variation"),
	P_RAB("RAB", "Repacking"),
	P_RAC("RAC", "Repair"),
	P_RAD("RAD", "Returnable container"),
	P_RAF("RAF", "Restocking"),
	P_RE("RE", "Re-delivery"),
	P_RF("RF", "Refurbishing"),
	P_RH("RH", "Rail wagon hire"),
	P_RV("RV", "Loading"),
	P_SA("SA", "Salvaging"),
	P_SAA("SAA", "Shipping and handling"),
	P_SAD("SAD", "Special packaging"),
	P_SAE("SAE", "Stamping"),
	P_SAI("SAI", "Consignee unload"),
	P_SG("SG", "Shrink-wrap"),
	P_SH("SH", "Special handling"),
	P_SM("SM", "Special finish"),
	P_SU("SU", "Set-up"),
	P_TAB("TAB", "Tank renting"),
	P_TAC("TAC", "Testing"),
	P_TT("TT", "Transportation - third party billing"),
	P_TV("TV", "Transportation by vendor"),
	P_V1("V1", "Drop yard"),
	P_V2("V2", "Drop dock"),
	P_WH("WH", "Warehousing"),
	P_XAA("XAA", "Combine all same day shipment"),
	P_YY("YY", "Split pick-up"),
	P_ZZZ("ZZZ", "Mutually defined");

	private final String code;
	private final String fullName;

	Uncl7161(String code, String fullName) {
		this.code = code;
		this.fullName = fullName;
	}

	public String getCode(){
		return code;
	}

	public String getFullName(){
		return fullName;
	}
}
