package sxr.model.codes;

public enum Iso4217 {
	P_AED("AED", "UAE Dirham"),
	P_AFN("AFN", "Afghani"),
	P_ALL("ALL", "Lek"),
	P_AMD("AMD", "Armenian Dram"),
	P_ANG("ANG", "Netherlands Antillean Guilder"),
	P_AOA("AOA", "Kwanza"),
	P_ARS("ARS", "Argentine Peso"),
	P_AUD("AUD", "Australian Dollar"),
	P_AWG("AWG", "Aruban Florin"),
	P_AZN("AZN", "Azerbaijan Manat"),
	P_BAM("BAM", "Convertible Mark"),
	P_BBD("BBD", "Barbados Dollar"),
	P_BDT("BDT", "Taka"),
	P_BGN("BGN", "Bulgarian Lev"),
	P_BHD("BHD", "Bahraini Dinar"),
	P_BIF("BIF", "Burundi Franc"),
	P_BMD("BMD", "Bermudian Dollar"),
	P_BND("BND", "Brunei Dollar"),
	P_BOB("BOB", "Boliviano"),
	P_BOV("BOV", "Mvdol"),
	P_BRL("BRL", "Brazilian Real"),
	P_BSD("BSD", "Bahamian Dollar"),
	P_BTN("BTN", "Ngultrum"),
	P_BWP("BWP", "Pula"),
	P_BYN("BYN", "Belarusian Ruble"),
	P_BZD("BZD", "Belize Dollar"),
	P_CAD("CAD", "Canadian Dollar"),
	P_CDF("CDF", "Congolese Franc"),
	P_CHE("CHE", "WIR Euro"),
	P_CHF("CHF", "Swiss Franc"),
	P_CHW("CHW", "WIR Franc"),
	P_CLF("CLF", "Unidad de Fomento"),
	P_CLP("CLP", "Chilean Peso"),
	P_CNY("CNY", "Yuan Renminbi"),
	P_COP("COP", "Colombian Peso"),
	P_COU("COU", "Unidad de Valor Real"),
	P_CRC("CRC", "Costa Rican Colon"),
	P_CUC("CUC", "Peso Convertible"),
	P_CUP("CUP", "Cuban Peso"),
	P_CVE("CVE", "Cabo Verde Escudo"),
	P_CZK("CZK", "Czech Koruna"),
	P_DJF("DJF", "Djibouti Franc"),
	P_DKK("DKK", "Danish Krone"),
	P_DOP("DOP", "Dominican Peso"),
	P_DZD("DZD", "Algerian Dinar"),
	P_EGP("EGP", "Egyptian Pound"),
	P_ERN("ERN", "Nakfa"),
	P_ETB("ETB", "Ethiopian Birr"),
	P_EUR("EUR", "Euro"),
	P_FJD("FJD", "Fiji Dollar"),
	P_FKP("FKP", "Falkland Islands Pound"),
	P_GBP("GBP", "Pound Sterling"),
	P_GEL("GEL", "Lari"),
	P_GHS("GHS", "Ghana Cedi"),
	P_GIP("GIP", "Gibraltar Pound"),
	P_GMD("GMD", "Dalasi"),
	P_GNF("GNF", "Guinean Franc"),
	P_GTQ("GTQ", "Quetzal"),
	P_GYD("GYD", "Guyana Dollar"),
	P_HKD("HKD", "Hong Kong Dollar"),
	P_HNL("HNL", "Lempira"),
	P_HRK("HRK", "Kuna"),
	P_HTG("HTG", "Gourde"),
	P_HUF("HUF", "Forint"),
	P_IDR("IDR", "Rupiah"),
	P_ILS("ILS", "New Israeli Sheqel"),
	P_INR("INR", "Indian Rupee"),
	P_IQD("IQD", "Iraqi Dinar"),
	P_IRR("IRR", "Iranian Rial"),
	P_ISK("ISK", "Iceland Krona"),
	P_JMD("JMD", "Jamaican Dollar"),
	P_JOD("JOD", "Jordanian Dinar"),
	P_JPY("JPY", "Yen"),
	P_KES("KES", "Kenyan Shilling"),
	P_KGS("KGS", "Som"),
	P_KHR("KHR", "Riel"),
	P_KMF("KMF", "Comorian Franc"),
	P_KPW("KPW", "North Korean Won"),
	P_KRW("KRW", "Won"),
	P_KWD("KWD", "Kuwaiti Dinar"),
	P_KYD("KYD", "Cayman Islands Dollar"),
	P_KZT("KZT", "Tenge"),
	P_LAK("LAK", "Lao Kip"),
	P_LBP("LBP", "Lebanese Pound"),
	P_LKR("LKR", "Sri Lanka Rupee"),
	P_LRD("LRD", "Liberian Dollar"),
	P_LSL("LSL", "Loti"),
	P_LYD("LYD", "Libyan Dinar"),
	P_MAD("MAD", "Moroccan Dirham"),
	P_MDL("MDL", "Moldovan Leu"),
	P_MGA("MGA", "Malagasy Ariary"),
	P_MKD("MKD", "Denar"),
	P_MMK("MMK", "Kyat"),
	P_MNT("MNT", "Tugrik"),
	P_MOP("MOP", "Pataca"),
	P_MRU("MRU", "Ouguiya"),
	P_MUR("MUR", "Mauritius Rupee"),
	P_MVR("MVR", "Rufiyaa"),
	P_MWK("MWK", "Malawi Kwacha"),
	P_MXN("MXN", "Mexican Peso"),
	P_MXV("MXV", "Mexican Unidad de Inversion (UDI)"),
	P_MYR("MYR", "Malaysian Ringgit"),
	P_MZN("MZN", "Mozambique Metical"),
	P_NAD("NAD", "Namibia Dollar"),
	P_NGN("NGN", "Naira"),
	P_NIO("NIO", "Cordoba Oro"),
	P_NOK("NOK", "Norwegian Krone"),
	P_NPR("NPR", "Nepalese Rupee"),
	P_NZD("NZD", "New Zealand Dollar"),
	P_OMR("OMR", "Rial Omani"),
	P_PAB("PAB", "Balboa"),
	P_PEN("PEN", "Sol"),
	P_PGK("PGK", "Kina"),
	P_PHP("PHP", "Philippine Piso"),
	P_PKR("PKR", "Pakistan Rupee"),
	P_PLN("PLN", "Zloty"),
	P_PYG("PYG", "Guarani"),
	P_QAR("QAR", "Qatari Rial"),
	P_RON("RON", "Romanian Leu"),
	P_RSD("RSD", "Serbian Dinar"),
	P_RUB("RUB", "Russian Ruble"),
	P_RWF("RWF", "Rwanda Franc"),
	P_SAR("SAR", "Saudi Riyal"),
	P_SBD("SBD", "Solomon Islands Dollar"),
	P_SCR("SCR", "Seychelles Rupee"),
	P_SDG("SDG", "Sudanese Pound"),
	P_SEK("SEK", "Swedish Krona"),
	P_SGD("SGD", "Singapore Dollar"),
	P_SHP("SHP", "Saint Helena Pound"),
	P_SLE("SLE", "Sierra Leone"),
	P_SOS("SOS", "Somali Shilling"),
	P_SRD("SRD", "Surinam Dollar"),
	P_SSP("SSP", "South Sudanese Pound"),
	P_STN("STN", "Dobra"),
	P_SVC("SVC", "El Salvador Colon"),
	P_SYP("SYP", "Syrian Pound"),
	P_SZL("SZL", "Lilangeni"),
	P_THB("THB", "Baht"),
	P_TJS("TJS", "Somoni"),
	P_TMT("TMT", "Turkmenistan New Manat"),
	P_TND("TND", "Tunisian Dinar"),
	P_TOP("TOP", "Pa’anga"),
	P_TRY("TRY", "Turkish Lira"),
	P_TTD("TTD", "Trinidad and Tobago Dollar"),
	P_TWD("TWD", "New Taiwan Dollar"),
	P_TZS("TZS", "Tanzanian Shilling"),
	P_UAH("UAH", "Hryvnia"),
	P_UGX("UGX", "Uganda Shilling"),
	P_USD("USD", "US Dollar"),
	P_USN("USN", "US Dollar (Next day)"),
	P_UYI("UYI", "Uruguay Peso en Unidades Indexadas (URUIURUI)"),
	P_UYU("UYU", "Peso Uruguayo"),
	P_UZS("UZS", "Uzbekistan Sum"),
	P_VEF("VEF", "Bolívar"),
	P_VND("VND", "Dong"),
	P_VUV("VUV", "Vatu"),
	P_WST("WST", "Tala"),
	P_XAF("XAF", "CFA Franc BEAC"),
	P_XAG("XAG", "Silver"),
	P_XAU("XAU", "Gold"),
	P_XBA("XBA", "Bond Markets Unit European Composite Unit (EURCO)"),
	P_XBB("XBB", "Bond Markets Unit European Monetary Unit (E.M.U.-6)"),
	P_XBC("XBC", "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)"),
	P_XBD("XBD", "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)"),
	P_XCD("XCD", "East Caribbean Dollar"),
	P_XDR("XDR", "SDR (Special Drawing Right)"),
	P_XOF("XOF", "CFA Franc BCEAO"),
	P_XPD("XPD", "Palladium"),
	P_XPF("XPF", "CFP Franc"),
	P_XPT("XPT", "Platinum"),
	P_XSU("XSU", "Sucre"),
	P_XTS("XTS", "Codes specifically reserved for testing purposes"),
	P_XUA("XUA", "ADB Unit of Account"),
	P_YER("YER", "Yemeni Rial"),
	P_ZAR("ZAR", "Rand"),
	P_ZMW("ZMW", "Zambian Kwacha"),
	P_ZWL("ZWL", "Zimbabwe Dollar");

	private final String code;
	private final String fullName;

	Iso4217(String code, String fullName) {
		this.code = code;
		this.fullName = fullName;
	}

	public String getCode(){
		return code;
	}

	public String getFullName(){
		return fullName;
	}
}
