/*********** GENERATED - DO NOT MODIFY ***********/
package sxr.core.model.codes;

public enum Uncl7143 {
	P_AA("AA", "Product version number"),
	P_AB("AB", "Assembly"),
	P_AC("AC", "HIBC (Health Industry Bar Code)"),
	P_AD("AD", "Cold roll number"),
	P_AE("AE", "Hot roll number"),
	P_AF("AF", "Slab number"),
	P_AG("AG", "Software revision number"),
	P_AH("AH", "UPC (Universal Product Code) Consumer package code (1-5-5)"),
	P_AI("AI", "UPC (Universal Product Code) Consumer package code (1-5-5-1)"),
	P_AJ("AJ", "Sample number"),
	P_AK("AK", "Pack number"),
	P_AL("AL", "UPC (Universal Product Code) Shipping container code (1-2-5-5)"),
	P_AM("AM", "UPC (Universal Product Code)/EAN (European article number) Shipping container code (1-2-5-5-1)"),
	P_AN("AN", "UPC (Universal Product Code) suffix"),
	P_AO("AO", "State label code"),
	P_AP("AP", "Heat number"),
	P_AQ("AQ", "Coupon number"),
	P_AR("AR", "Resource number"),
	P_AS("AS", "Work task number"),
	P_AT("AT", "Price look up number"),
	P_AU("AU", "NSN (North Atlantic Treaty Organization Stock Number)"),
	P_AV("AV", "Refined product code"),
	P_AW("AW", "Exhibit"),
	P_AX("AX", "End item"),
	P_AY("AY", "Federal supply classification"),
	P_AZ("AZ", "Engineering data list"),
	P_BA("BA", "Milestone event number"),
	P_BB("BB", "Lot number"),
	P_BC("BC", "National drug code 4-4-2 format"),
	P_BD("BD", "National drug code 5-3-2 format"),
	P_BE("BE", "National drug code 5-4-1 format"),
	P_BF("BF", "National drug code 5-4-2 format"),
	P_BG("BG", "National drug code"),
	P_BH("BH", "Part number"),
	P_BI("BI", "Local Stock Number (LSN)"),
	P_BJ("BJ", "Next higher assembly number"),
	P_BK("BK", "Data category"),
	P_BL("BL", "Control number"),
	P_BM("BM", "Special material identification code"),
	P_BN("BN", "Locally assigned control number"),
	P_BO("BO", "Buyer's colour"),
	P_BP("BP", "Buyer's part number"),
	P_BQ("BQ", "Variable measure product code"),
	P_BR("BR", "Financial phase"),
	P_BS("BS", "Contract breakdown"),
	P_BT("BT", "Technical phase"),
	P_BU("BU", "Dye lot number"),
	P_BV("BV", "Daily statement of activities"),
	P_BW("BW", "Periodical statement of activities within a bilaterally agreed time period"),
	P_BX("BX", "Calendar week statement of activities"),
	P_BY("BY", "Calendar month statement of activities"),
	P_BZ("BZ", "Original equipment number"),
	P_CC("CC", "Industry commodity code"),
	P_CG("CG", "Commodity grouping"),
	P_CL("CL", "Colour number"),
	P_CR("CR", "Contract number"),
	P_CV("CV", "Customs article number"),
	P_DR("DR", "Drawing revision number"),
	P_DW("DW", "Drawing"),
	P_EC("EC", "Engineering change level"),
	P_EF("EF", "Material code"),
	P_EMD("EMD", "EMDN (European Medical Device Nomenclature)"),
	P_EN("EN", "International Article Numbering Association (EAN)"),
	P_FS("FS", "Fish species"),
	P_GB("GB", "Buyer's internal product group code"),
	P_GMN("GMN", "Global model number"),
	P_GN("GN", "National product group code"),
	P_GS("GS", "General specification number"),
	P_HS("HS", "Harmonised system"),
	P_IB("IB", "ISBN (International Standard Book Number)"),
	P_IN("IN", "Buyer's item number"),
	P_IS("IS", "ISSN (International Standard Serial Number)"),
	P_IT("IT", "Buyer's style number"),
	P_IZ("IZ", "Buyer's size code"),
	P_MA("MA", "Machine number"),
	P_MF("MF", "Manufacturer's (producer's) article number"),
	P_MN("MN", "Model number"),
	P_MP("MP", "Product/service identification number"),
	P_NB("NB", "Batch number"),
	P_ON("ON", "Customer order number"),
	P_PD("PD", "Part number description"),
	P_PL("PL", "Purchaser's order line number"),
	P_PO("PO", "Purchase order number"),
	P_PV("PV", "Promotional variant number"),
	P_QS("QS", "Buyer's qualifier for size"),
	P_RC("RC", "Returnable container number"),
	P_RN("RN", "Release number"),
	P_RU("RU", "Run number"),
	P_RY("RY", "Record keeping of model year"),
	P_SA("SA", "Supplier's article number"),
	P_SG("SG", "Standard group of products (mixed assortment)"),
	P_SK("SK", "SKU (Stock keeping unit)"),
	P_SN("SN", "Serial number"),
	P_SRS("SRS", "RSK number"),
	P_SRT("SRT", "IFLS (Institut Francais du Libre Service) 5 digit product classification code"),
	P_SRU("SRU", "IFLS (Institut Francais du Libre Service) 9 digit product classification code"),
	P_SRV("SRV", "GS1 Global Trade Item Number"),
	P_SRW("SRW", "EDIS (Energy Data Identification System)"),
	P_SRX("SRX", "Slaughter number"),
	P_SRY("SRY", "Official animal number"),
	P_SRZ("SRZ", "Harmonized tariff schedule"),
	P_SS("SS", "Supplier's supplier article number"),
	P_SSA("SSA", "46 Level DOT Code"),
	P_SSB("SSB", "Airline Tariff 6D"),
	P_SSC("SSC", "Title 49 Code of Federal Regulations"),
	P_SSD("SSD", "International Civil Aviation Administration code"),
	P_SSE("SSE", "Hazardous Materials ID DOT"),
	P_SSF("SSF", "Endorsement"),
	P_SSG("SSG", "Air Force Regulation 71-4"),
	P_SSH("SSH", "Breed"),
	P_SSI("SSI", "Chemical Abstract Service (CAS) registry number"),
	P_SSJ("SSJ", "Engine model designation"),
	P_SSK("SSK", "Institutional Meat Purchase Specifications (IMPS) Number"),
	P_SSL("SSL", "Price Look-Up code (PLU)"),
	P_SSM("SSM", "International Maritime Organization (IMO) Code"),
	P_SSN("SSN", "Bureau of Explosives 600-A (rail)"),
	P_SSO("SSO", "United Nations Dangerous Goods List"),
	P_SSP("SSP", "International Code of Botanical Nomenclature (ICBN)"),
	P_SSQ("SSQ", "International Code of Zoological Nomenclature (ICZN)"),
	P_SSR("SSR", "International Code of Nomenclature for Cultivated Plants (ICNCP)"),
	P_SSS("SSS", "Distributor’s article identifier"),
	P_SST("SST", "Norwegian Classification system ENVA"),
	P_SSU("SSU", "Supplier assigned classification"),
	P_SSV("SSV", "Mexican classification system AMECE"),
	P_SSW("SSW", "German classification system CCG"),
	P_SSX("SSX", "Finnish classification system EANFIN"),
	P_SSY("SSY", "Canadian classification system ICC"),
	P_SSZ("SSZ", "French classification system IFLS5"),
	P_ST("ST", "Style number"),
	P_STA("STA", "Dutch classification system CBL"),
	P_STB("STB", "Japanese classification system JICFS"),
	P_STC("STC", "European Union dairy subsidy eligibility classification"),
	P_STD("STD", "GS1 Spain classification system"),
	P_STE("STE", "GS1 Poland classification system"),
	P_STF("STF", "Federal Agency on Technical Regulating and Metrology of the Russian Federation"),
	P_STG("STG", "Efficient Consumer Response (ECR) Austria classification system"),
	P_STH("STH", "GS1 Italy classification system"),
	P_STI("STI", "CPV (Common Procurement Vocabulary)"),
	P_STJ("STJ", "IFDA (International Foodservice Distributors Association)"),
	P_STK("STK", "AHFS (American Hospital Formulary Service) pharmacologic -therapeutic classification"),
	P_STL("STL", "ATC (Anatomical Therapeutic Chemical) classification system"),
	P_STM("STM", "CLADIMED (Classification des Dispositifs Médicaux)"),
	P_STN("STN", "CMDR (Canadian Medical Device Regulations) classification system"),
	P_STO("STO", "CNDM (Classificazione Nazionale dei Dispositivi Medici)"),
	P_STP("STP", "UK DM&D (Dictionary of Medicines & Devices) standard coding scheme"),
	P_STQ("STQ", "eCl@ss"),
	P_STR("STR", "EDMA (European Diagnostic Manufacturers Association) Product Classification"),
	P_STS("STS", "EGAR (European Generic Article Register)"),
	P_STT("STT", "GMDN (Global Medical Devices Nomenclature)"),
	P_STU("STU", "GPI (Generic Product Identifier)"),
	P_STV("STV", "HCPCS (Healthcare Common Procedure Coding System)"),
	P_STW("STW", "ICPS (International Classification for Patient Safety)"),
	P_STX("STX", "MedDRA (Medical Dictionary for Regulatory Activities)"),
	P_STY("STY", "Medical Columbus"),
	P_STZ("STZ", "NAPCS (North American Product Classification System)"),
	P_SUA("SUA", "NHS (National Health Services) eClass"),
	P_SUB("SUB", "US FDA (Food and Drug Administration) Product Code Classification Database"),
	P_SUC("SUC", "SNOMED CT (Systematized Nomenclature of Medicine-Clinical Terms)"),
	P_SUD("SUD", "UMDNS (Universal Medical Device Nomenclature System)"),
	P_SUE("SUE", "GS1 Global Returnable Asset Identifier, non-serialised"),
	P_SUF("SUF", "IMEI"),
	P_SUG("SUG", "Waste Type (EMSA)"),
	P_SUH("SUH", "Ship's store classification type"),
	P_SUI("SUI", "Emergency fire code"),
	P_SUJ("SUJ", "Emergency spillage code"),
	P_SUK("SUK", "IMDG packing group"),
	P_SUL("SUL", "MARPOL Code IBC"),
	P_SUM("SUM", "IMDG subsidiary risk class"),
	P_TG("TG", "Transport group number"),
	P_TSN("TSN", "Taxonomic Serial Number"),
	P_TSO("TSO", "IMDG main hazard class"),
	P_TSP("TSP", "EU Combined Nomenclature"),
	P_TSQ("TSQ", "Therapeutic classification number"),
	P_TSR("TSR", "European Waste Catalogue"),
	P_TSS("TSS", "Price grouping code"),
	P_TST("TST", "UNSPSC"),
	P_TSU("TSU", "EU RoHS Directive"),
	P_UA("UA", "Ultimate customer's article number"),
	P_UP("UP", "UPC (Universal product code)"),
	P_VN("VN", "Vendor item number"),
	P_VP("VP", "Vendor's (seller's) part number"),
	P_VS("VS", "Vendor's supplemental item number"),
	P_VX("VX", "Vendor specification number"),
	P_ZZZ("ZZZ", "Mutually defined");

	private final String code;
	private final String fullName;

	Uncl7143(String code, String fullName) {
		this.code = code;
		this.fullName = fullName;
	}

	public String getCode(){
		return code;
	}

	public String getFullName(){
		return fullName;
	}
}
