/*********** GENERATED - DO NOT MODIFY ***********/
package sxr.core.model.codes;

public enum Unecerec20 {
	P_10("10", "group"),
	P_11("11", "outfit"),
	P_13("13", "ration"),
	P_14("14", "shot"),
	P_15("15", "stick, military"),
	P_20("20", "twenty foot container"),
	P_21("21", "forty foot container"),
	P_22("22", "decilitre per gram"),
	P_23("23", "gram per cubic centimetre"),
	P_24("24", "theoretical pound"),
	P_25("25", "gram per square centimetre"),
	P_27("27", "theoretical ton"),
	P_28("28", "kilogram per square metre"),
	P_33("33", "kilopascal square metre per gram"),
	P_34("34", "kilopascal per millimetre"),
	P_35("35", "millilitre per square centimetre second"),
	P_37("37", "ounce per square foot"),
	P_38("38", "ounce per square foot per 0,01inch"),
	P_40("40", "millilitre per second"),
	P_41("41", "millilitre per minute"),
	P_56("56", "sitas"),
	P_57("57", "mesh"),
	P_58("58", "net kilogram"),
	P_59("59", "part per million"),
	P_60("60", "percent weight"),
	P_61("61", "part per billion (US)"),
	P_74("74", "millipascal"),
	P_77("77", "milli-inch"),
	P_80("80", "pound per square inch absolute"),
	P_81("81", "henry"),
	P_85("85", "foot pound-force"),
	P_87("87", "pound per cubic foot"),
	P_89("89", "poise"),
	P_91("91", "stokes"),
	P_1I("1I", "fixed rate"),
	P_2A("2A", "radian per second"),
	P_2B("2B", "radian per second squared"),
	P_2C("2C", "roentgen"),
	P_2G("2G", "volt AC"),
	P_2H("2H", "volt DC"),
	P_2I("2I", "British thermal unit (international table) per hour"),
	P_2J("2J", "cubic centimetre per second"),
	P_2K("2K", "cubic foot per hour"),
	P_2L("2L", "cubic foot per minute"),
	P_2M("2M", "centimetre per second"),
	P_2N("2N", "decibel"),
	P_2P("2P", "kilobyte"),
	P_2Q("2Q", "kilobecquerel"),
	P_2R("2R", "kilocurie"),
	P_2U("2U", "megagram"),
	P_2X("2X", "metre per minute"),
	P_2Y("2Y", "milliroentgen"),
	P_2Z("2Z", "millivolt"),
	P_3B("3B", "megajoule"),
	P_3C("3C", "manmonth"),
	P_4C("4C", "centistokes"),
	P_4G("4G", "microlitre"),
	P_4H("4H", "micrometre (micron)"),
	P_4K("4K", "milliampere"),
	P_4L("4L", "megabyte"),
	P_4M("4M", "milligram per hour"),
	P_4N("4N", "megabecquerel"),
	P_4O("4O", "microfarad"),
	P_4P("4P", "newton per metre"),
	P_4Q("4Q", "ounce inch"),
	P_4R("4R", "ounce foot"),
	P_4T("4T", "picofarad"),
	P_4U("4U", "pound per hour"),
	P_4W("4W", "ton (US) per hour"),
	P_4X("4X", "kilolitre per hour"),
	P_5A("5A", "barrel (US) per minute"),
	P_5B("5B", "batch"),
	P_5E("5E", "MMSCF/day"),
	P_5J("5J", "hydraulic horse power"),
	P_A10("A10", "ampere square metre per joule second"),
	P_A11("A11", "angstrom"),
	P_A12("A12", "astronomical unit"),
	P_A13("A13", "attojoule"),
	P_A14("A14", "barn"),
	P_A15("A15", "barn per electronvolt"),
	P_A16("A16", "barn per steradian electronvolt"),
	P_A17("A17", "barn per steradian"),
	P_A18("A18", "becquerel per kilogram"),
	P_A19("A19", "becquerel per cubic metre"),
	P_A2("A2", "ampere per centimetre"),
	P_A20("A20", "British thermal unit (international table) per second square foot degree Rankine"),
	P_A21("A21", "British thermal unit (international table) per pound degree Rankine"),
	P_A22("A22", "British thermal unit (international table) per second foot degree Rankine"),
	P_A23("A23", "British thermal unit (international table) per hour square foot degree Rankine"),
	P_A24("A24", "candela per square metre"),
	P_A26("A26", "coulomb metre"),
	P_A27("A27", "coulomb metre squared per volt"),
	P_A28("A28", "coulomb per cubic centimetre"),
	P_A29("A29", "coulomb per cubic metre"),
	P_A3("A3", "ampere per millimetre"),
	P_A30("A30", "coulomb per cubic millimetre"),
	P_A31("A31", "coulomb per kilogram second"),
	P_A32("A32", "coulomb per mole"),
	P_A33("A33", "coulomb per square centimetre"),
	P_A34("A34", "coulomb per square metre"),
	P_A35("A35", "coulomb per square millimetre"),
	P_A36("A36", "cubic centimetre per mole"),
	P_A37("A37", "cubic decimetre per mole"),
	P_A38("A38", "cubic metre per coulomb"),
	P_A39("A39", "cubic metre per kilogram"),
	P_A4("A4", "ampere per square centimetre"),
	P_A40("A40", "cubic metre per mole"),
	P_A41("A41", "ampere per square metre"),
	P_A42("A42", "curie per kilogram"),
	P_A43("A43", "deadweight tonnage"),
	P_A44("A44", "decalitre"),
	P_A45("A45", "decametre"),
	P_A47("A47", "decitex"),
	P_A48("A48", "degree Rankine"),
	P_A49("A49", "denier"),
	P_A5("A5", "ampere square metre"),
	P_A53("A53", "electronvolt"),
	P_A54("A54", "electronvolt per metre"),
	P_A55("A55", "electronvolt square metre"),
	P_A56("A56", "electronvolt square metre per kilogram"),
	P_A59("A59", "8-part cloud cover"),
	P_A6("A6", "ampere per square metre kelvin squared"),
	P_A68("A68", "exajoule"),
	P_A69("A69", "farad per metre"),
	P_A7("A7", "ampere per square millimetre"),
	P_A70("A70", "femtojoule"),
	P_A71("A71", "femtometre"),
	P_A73("A73", "foot per second squared"),
	P_A74("A74", "foot pound-force per second"),
	P_A75("A75", "freight ton"),
	P_A76("A76", "gal"),
	P_A8("A8", "ampere second"),
	P_A84("A84", "gigacoulomb per cubic metre"),
	P_A85("A85", "gigaelectronvolt"),
	P_A86("A86", "gigahertz"),
	P_A87("A87", "gigaohm"),
	P_A88("A88", "gigaohm metre"),
	P_A89("A89", "gigapascal"),
	P_A9("A9", "rate"),
	P_A90("A90", "gigawatt"),
	P_A91("A91", "gon"),
	P_A93("A93", "gram per cubic metre"),
	P_A94("A94", "gram per mole"),
	P_A95("A95", "gray"),
	P_A96("A96", "gray per second"),
	P_A97("A97", "hectopascal"),
	P_A98("A98", "henry per metre"),
	P_A99("A99", "bit"),
	P_AA("AA", "ball"),
	P_AB("AB", "bulk pack"),
	P_ACR("ACR", "acre"),
	P_ACT("ACT", "activity"),
	P_AD("AD", "byte"),
	P_AE("AE", "ampere per metre"),
	P_AH("AH", "additional minute"),
	P_AI("AI", "average minute per call"),
	P_AK("AK", "fathom"),
	P_AL("AL", "access line"),
	P_AMH("AMH", "ampere hour"),
	P_AMP("AMP", "ampere"),
	P_ANN("ANN", "year"),
	P_APZ("APZ", "troy ounce or apothecary ounce"),
	P_AQ("AQ", "anti-hemophilic factor (AHF) unit"),
	P_AS("AS", "assortment"),
	P_ASM("ASM", "alcoholic strength by mass"),
	P_ASU("ASU", "alcoholic strength by volume"),
	P_ATM("ATM", "standard atmosphere"),
	P_AWG("AWG", "american wire gauge"),
	P_AY("AY", "assembly"),
	P_AZ("AZ", "British thermal unit (international table) per pound"),
	P_B1("B1", "barrel (US) per day"),
	P_B10("B10", "bit per second"),
	P_B11("B11", "joule per kilogram kelvin"),
	P_B12("B12", "joule per metre"),
	P_B13("B13", "joule per square metre"),
	P_B14("B14", "joule per metre to the fourth power"),
	P_B15("B15", "joule per mole"),
	P_B16("B16", "joule per mole kelvin"),
	P_B17("B17", "credit"),
	P_B18("B18", "joule second"),
	P_B19("B19", "digit"),
	P_B20("B20", "joule square metre per kilogram"),
	P_B21("B21", "kelvin per watt"),
	P_B22("B22", "kiloampere"),
	P_B23("B23", "kiloampere per square metre"),
	P_B24("B24", "kiloampere per metre"),
	P_B25("B25", "kilobecquerel per kilogram"),
	P_B26("B26", "kilocoulomb"),
	P_B27("B27", "kilocoulomb per cubic metre"),
	P_B28("B28", "kilocoulomb per square metre"),
	P_B29("B29", "kiloelectronvolt"),
	P_B3("B3", "batting pound"),
	P_B30("B30", "gibibit"),
	P_B31("B31", "kilogram metre per second"),
	P_B32("B32", "kilogram metre squared"),
	P_B33("B33", "kilogram metre squared per second"),
	P_B34("B34", "kilogram per cubic decimetre"),
	P_B35("B35", "kilogram per litre"),
	P_B4("B4", "barrel, imperial"),
	P_B41("B41", "kilojoule per kelvin"),
	P_B42("B42", "kilojoule per kilogram"),
	P_B43("B43", "kilojoule per kilogram kelvin"),
	P_B44("B44", "kilojoule per mole"),
	P_B45("B45", "kilomole"),
	P_B46("B46", "kilomole per cubic metre"),
	P_B47("B47", "kilonewton"),
	P_B48("B48", "kilonewton metre"),
	P_B49("B49", "kiloohm"),
	P_B50("B50", "kiloohm metre"),
	P_B52("B52", "kilosecond"),
	P_B53("B53", "kilosiemens"),
	P_B54("B54", "kilosiemens per metre"),
	P_B55("B55", "kilovolt per metre"),
	P_B56("B56", "kiloweber per metre"),
	P_B57("B57", "light year"),
	P_B58("B58", "litre per mole"),
	P_B59("B59", "lumen hour"),
	P_B60("B60", "lumen per square metre"),
	P_B61("B61", "lumen per watt"),
	P_B62("B62", "lumen second"),
	P_B63("B63", "lux hour"),
	P_B64("B64", "lux second"),
	P_B66("B66", "megaampere per square metre"),
	P_B67("B67", "megabecquerel per kilogram"),
	P_B68("B68", "gigabit"),
	P_B69("B69", "megacoulomb per cubic metre"),
	P_B7("B7", "cycle"),
	P_B70("B70", "megacoulomb per square metre"),
	P_B71("B71", "megaelectronvolt"),
	P_B72("B72", "megagram per cubic metre"),
	P_B73("B73", "meganewton"),
	P_B74("B74", "meganewton metre"),
	P_B75("B75", "megaohm"),
	P_B76("B76", "megaohm metre"),
	P_B77("B77", "megasiemens per metre"),
	P_B78("B78", "megavolt"),
	P_B79("B79", "megavolt per metre"),
	P_B8("B8", "joule per cubic metre"),
	P_B80("B80", "gigabit per second"),
	P_B81("B81", "reciprocal metre squared reciprocal second"),
	P_B82("B82", "inch per linear foot"),
	P_B83("B83", "metre to the fourth power"),
	P_B84("B84", "microampere"),
	P_B85("B85", "microbar"),
	P_B86("B86", "microcoulomb"),
	P_B87("B87", "microcoulomb per cubic metre"),
	P_B88("B88", "microcoulomb per square metre"),
	P_B89("B89", "microfarad per metre"),
	P_B90("B90", "microhenry"),
	P_B91("B91", "microhenry per metre"),
	P_B92("B92", "micronewton"),
	P_B93("B93", "micronewton metre"),
	P_B94("B94", "microohm"),
	P_B95("B95", "microohm metre"),
	P_B96("B96", "micropascal"),
	P_B97("B97", "microradian"),
	P_B98("B98", "microsecond"),
	P_B99("B99", "microsiemens"),
	P_BAR("BAR", "bar [unit of pressure]"),
	P_BB("BB", "base box"),
	P_BFT("BFT", "board foot"),
	P_BHP("BHP", "brake horse power"),
	P_BIL("BIL", "billion (EUR)"),
	P_BLD("BLD", "dry barrel (US)"),
	P_BLL("BLL", "barrel (US)"),
	P_BP("BP", "hundred board foot"),
	P_BPM("BPM", "beats per minute"),
	P_BQL("BQL", "becquerel"),
	P_BTU("BTU", "British thermal unit (international table)"),
	P_BUA("BUA", "bushel (US)"),
	P_BUI("BUI", "bushel (UK)"),
	P_C0("C0", "call"),
	P_C10("C10", "millifarad"),
	P_C11("C11", "milligal"),
	P_C12("C12", "milligram per metre"),
	P_C13("C13", "milligray"),
	P_C14("C14", "millihenry"),
	P_C15("C15", "millijoule"),
	P_C16("C16", "millimetre per second"),
	P_C17("C17", "millimetre squared per second"),
	P_C18("C18", "millimole"),
	P_C19("C19", "mole per kilogram"),
	P_C20("C20", "millinewton"),
	P_C21("C21", "kibibit"),
	P_C22("C22", "millinewton per metre"),
	P_C23("C23", "milliohm metre"),
	P_C24("C24", "millipascal second"),
	P_C25("C25", "milliradian"),
	P_C26("C26", "millisecond"),
	P_C27("C27", "millisiemens"),
	P_C28("C28", "millisievert"),
	P_C29("C29", "millitesla"),
	P_C3("C3", "microvolt per metre"),
	P_C30("C30", "millivolt per metre"),
	P_C31("C31", "milliwatt"),
	P_C32("C32", "milliwatt per square metre"),
	P_C33("C33", "milliweber"),
	P_C34("C34", "mole"),
	P_C35("C35", "mole per cubic decimetre"),
	P_C36("C36", "mole per cubic metre"),
	P_C37("C37", "kilobit"),
	P_C38("C38", "mole per litre"),
	P_C39("C39", "nanoampere"),
	P_C40("C40", "nanocoulomb"),
	P_C41("C41", "nanofarad"),
	P_C42("C42", "nanofarad per metre"),
	P_C43("C43", "nanohenry"),
	P_C44("C44", "nanohenry per metre"),
	P_C45("C45", "nanometre"),
	P_C46("C46", "nanoohm metre"),
	P_C47("C47", "nanosecond"),
	P_C48("C48", "nanotesla"),
	P_C49("C49", "nanowatt"),
	P_C50("C50", "neper"),
	P_C51("C51", "neper per second"),
	P_C52("C52", "picometre"),
	P_C53("C53", "newton metre second"),
	P_C54("C54", "newton metre squared per kilogram squared"),
	P_C55("C55", "newton per square metre"),
	P_C56("C56", "newton per square millimetre"),
	P_C57("C57", "newton second"),
	P_C58("C58", "newton second per metre"),
	P_C59("C59", "octave"),
	P_C60("C60", "ohm centimetre"),
	P_C61("C61", "ohm metre"),
	P_C62("C62", "one"),
	P_C63("C63", "parsec"),
	P_C64("C64", "pascal per kelvin"),
	P_C65("C65", "pascal second"),
	P_C66("C66", "pascal second per cubic metre"),
	P_C67("C67", "pascal second per metre"),
	P_C68("C68", "petajoule"),
	P_C69("C69", "phon"),
	P_C7("C7", "centipoise"),
	P_C70("C70", "picoampere"),
	P_C71("C71", "picocoulomb"),
	P_C72("C72", "picofarad per metre"),
	P_C73("C73", "picohenry"),
	P_C74("C74", "kilobit per second"),
	P_C75("C75", "picowatt"),
	P_C76("C76", "picowatt per square metre"),
	P_C78("C78", "pound-force"),
	P_C79("C79", "kilovolt ampere hour"),
	P_C8("C8", "millicoulomb per kilogram"),
	P_C80("C80", "rad"),
	P_C81("C81", "radian"),
	P_C82("C82", "radian square metre per mole"),
	P_C83("C83", "radian square metre per kilogram"),
	P_C84("C84", "radian per metre"),
	P_C85("C85", "reciprocal angstrom"),
	P_C86("C86", "reciprocal cubic metre"),
	P_C87("C87", "reciprocal cubic metre per second"),
	P_C88("C88", "reciprocal electron volt per cubic metre"),
	P_C89("C89", "reciprocal henry"),
	P_C9("C9", "coil group"),
	P_C90("C90", "reciprocal joule per cubic metre"),
	P_C91("C91", "reciprocal kelvin or kelvin to the power minus one"),
	P_C92("C92", "reciprocal metre"),
	P_C93("C93", "reciprocal square metre"),
	P_C94("C94", "reciprocal minute"),
	P_C95("C95", "reciprocal mole"),
	P_C96("C96", "reciprocal pascal or pascal to the power minus one"),
	P_C97("C97", "reciprocal second"),
	P_C99("C99", "reciprocal second per metre squared"),
	P_CCT("CCT", "carrying capacity in metric ton"),
	P_CDL("CDL", "candela"),
	P_CEL("CEL", "degree Celsius"),
	P_CEN("CEN", "hundred"),
	P_CG("CG", "card"),
	P_CGM("CGM", "centigram"),
	P_CKG("CKG", "coulomb per kilogram"),
	P_CLF("CLF", "hundred leave"),
	P_CLT("CLT", "centilitre"),
	P_CMK("CMK", "square centimetre"),
	P_CMQ("CMQ", "cubic centimetre"),
	P_CMT("CMT", "centimetre"),
	P_CNP("CNP", "hundred pack"),
	P_CNT("CNT", "cental (UK)"),
	P_COU("COU", "coulomb"),
	P_CTG("CTG", "content gram"),
	P_CTM("CTM", "metric carat"),
	P_CTN("CTN", "content ton (metric)"),
	P_CUR("CUR", "curie"),
	P_CWA("CWA", "hundred pound (cwt) / hundred weight (US)"),
	P_CWI("CWI", "hundred weight (UK)"),
	P_D03("D03", "kilowatt hour per hour"),
	P_D04("D04", "lot [unit of weight]"),
	P_D1("D1", "reciprocal second per steradian"),
	P_D10("D10", "siemens per metre"),
	P_D11("D11", "mebibit"),
	P_D12("D12", "siemens square metre per mole"),
	P_D13("D13", "sievert"),
	P_D15("D15", "sone"),
	P_D16("D16", "square centimetre per erg"),
	P_D17("D17", "square centimetre per steradian erg"),
	P_D18("D18", "metre kelvin"),
	P_D19("D19", "square metre kelvin per watt"),
	P_D2("D2", "reciprocal second per steradian metre squared"),
	P_D20("D20", "square metre per joule"),
	P_D21("D21", "square metre per kilogram"),
	P_D22("D22", "square metre per mole"),
	P_D23("D23", "pen gram (protein)"),
	P_D24("D24", "square metre per steradian"),
	P_D25("D25", "square metre per steradian joule"),
	P_D26("D26", "square metre per volt second"),
	P_D27("D27", "steradian"),
	P_D29("D29", "terahertz"),
	P_D30("D30", "terajoule"),
	P_D31("D31", "terawatt"),
	P_D32("D32", "terawatt hour"),
	P_D33("D33", "tesla"),
	P_D34("D34", "tex"),
	P_D36("D36", "megabit"),
	P_D41("D41", "tonne per cubic metre"),
	P_D42("D42", "tropical year"),
	P_D43("D43", "unified atomic mass unit"),
	P_D44("D44", "var"),
	P_D45("D45", "volt squared per kelvin squared"),
	P_D46("D46", "volt - ampere"),
	P_D47("D47", "volt per centimetre"),
	P_D48("D48", "volt per kelvin"),
	P_D49("D49", "millivolt per kelvin"),
	P_D5("D5", "kilogram per square centimetre"),
	P_D50("D50", "volt per metre"),
	P_D51("D51", "volt per millimetre"),
	P_D52("D52", "watt per kelvin"),
	P_D53("D53", "watt per metre kelvin"),
	P_D54("D54", "watt per square metre"),
	P_D55("D55", "watt per square metre kelvin"),
	P_D56("D56", "watt per square metre kelvin to the fourth power"),
	P_D57("D57", "watt per steradian"),
	P_D58("D58", "watt per steradian square metre"),
	P_D59("D59", "weber per metre"),
	P_D6("D6", "roentgen per second"),
	P_D60("D60", "weber per millimetre"),
	P_D61("D61", "minute [unit of angle]"),
	P_D62("D62", "second [unit of angle]"),
	P_D63("D63", "book"),
	P_D65("D65", "round"),
	P_D68("D68", "number of words"),
	P_D69("D69", "inch to the fourth power"),
	P_D73("D73", "joule square metre"),
	P_D74("D74", "kilogram per mole"),
	P_D77("D77", "megacoulomb"),
	P_D78("D78", "megajoule per second"),
	P_D80("D80", "microwatt"),
	P_D81("D81", "microtesla"),
	P_D82("D82", "microvolt"),
	P_D83("D83", "millinewton metre"),
	P_D85("D85", "microwatt per square metre"),
	P_D86("D86", "millicoulomb"),
	P_D87("D87", "millimole per kilogram"),
	P_D88("D88", "millicoulomb per cubic metre"),
	P_D89("D89", "millicoulomb per square metre"),
	P_D91("D91", "rem"),
	P_D93("D93", "second per cubic metre"),
	P_D94("D94", "second per cubic metre radian"),
	P_D95("D95", "joule per gram"),
	P_DAA("DAA", "decare"),
	P_DAD("DAD", "ten day"),
	P_DAY("DAY", "day"),
	P_DB("DB", "dry pound"),
	P_DBM("DBM", "Decibel-milliwatts"),
	P_DBW("DBW", "Decibel watt"),
	P_DD("DD", "degree [unit of angle]"),
	P_DEC("DEC", "decade"),
	P_DG("DG", "decigram"),
	P_DJ("DJ", "decagram"),
	P_DLT("DLT", "decilitre"),
	P_DMA("DMA", "cubic decametre"),
	P_DMK("DMK", "square decimetre"),
	P_DMO("DMO", "standard kilolitre"),
	P_DMQ("DMQ", "cubic decimetre"),
	P_DMT("DMT", "decimetre"),
	P_DN("DN", "decinewton metre"),
	P_DPC("DPC", "dozen piece"),
	P_DPR("DPR", "dozen pair"),
	P_DPT("DPT", "displacement tonnage"),
	P_DRA("DRA", "dram (US)"),
	P_DRI("DRI", "dram (UK)"),
	P_DRL("DRL", "dozen roll"),
	P_DT("DT", "dry ton"),
	P_DTN("DTN", "decitonne"),
	P_DWT("DWT", "pennyweight"),
	P_DZN("DZN", "dozen"),
	P_DZP("DZP", "dozen pack"),
	P_E01("E01", "newton per square centimetre"),
	P_E07("E07", "megawatt hour per hour"),
	P_E08("E08", "megawatt per hertz"),
	P_E09("E09", "milliampere hour"),
	P_E10("E10", "degree day"),
	P_E12("E12", "mille"),
	P_E14("E14", "kilocalorie (international table)"),
	P_E15("E15", "kilocalorie (thermochemical) per hour"),
	P_E16("E16", "million Btu(IT) per hour"),
	P_E17("E17", "cubic foot per second"),
	P_E18("E18", "tonne per hour"),
	P_E19("E19", "ping"),
	P_E20("E20", "megabit per second"),
	P_E21("E21", "shares"),
	P_E22("E22", "TEU"),
	P_E23("E23", "tyre"),
	P_E25("E25", "active unit"),
	P_E27("E27", "dose"),
	P_E28("E28", "air dry ton"),
	P_E30("E30", "strand"),
	P_E31("E31", "square metre per litre"),
	P_E32("E32", "litre per hour"),
	P_E33("E33", "foot per thousand"),
	P_E34("E34", "gigabyte"),
	P_E35("E35", "terabyte"),
	P_E36("E36", "petabyte"),
	P_E37("E37", "pixel"),
	P_E38("E38", "megapixel"),
	P_E39("E39", "dots per inch"),
	P_E4("E4", "gross kilogram"),
	P_E40("E40", "part per hundred thousand"),
	P_E41("E41", "kilogram-force per square millimetre"),
	P_E42("E42", "kilogram-force per square centimetre"),
	P_E43("E43", "joule per square centimetre"),
	P_E44("E44", "kilogram-force metre per square centimetre"),
	P_E45("E45", "milliohm"),
	P_E46("E46", "kilowatt hour per cubic metre"),
	P_E47("E47", "kilowatt hour per kelvin"),
	P_E48("E48", "service unit"),
	P_E49("E49", "working day"),
	P_E50("E50", "accounting unit"),
	P_E51("E51", "job"),
	P_E52("E52", "run foot"),
	P_E53("E53", "test"),
	P_E54("E54", "trip"),
	P_E55("E55", "use"),
	P_E56("E56", "well"),
	P_E57("E57", "zone"),
	P_E58("E58", "exabit per second"),
	P_E59("E59", "exbibyte"),
	P_E60("E60", "pebibyte"),
	P_E61("E61", "tebibyte"),
	P_E62("E62", "gibibyte"),
	P_E63("E63", "mebibyte"),
	P_E64("E64", "kibibyte"),
	P_E65("E65", "exbibit per metre"),
	P_E66("E66", "exbibit per square metre"),
	P_E67("E67", "exbibit per cubic metre"),
	P_E68("E68", "gigabyte per second"),
	P_E69("E69", "gibibit per metre"),
	P_E70("E70", "gibibit per square metre"),
	P_E71("E71", "gibibit per cubic metre"),
	P_E72("E72", "kibibit per metre"),
	P_E73("E73", "kibibit per square metre"),
	P_E74("E74", "kibibit per cubic metre"),
	P_E75("E75", "mebibit per metre"),
	P_E76("E76", "mebibit per square metre"),
	P_E77("E77", "mebibit per cubic metre"),
	P_E78("E78", "petabit"),
	P_E79("E79", "petabit per second"),
	P_E80("E80", "pebibit per metre"),
	P_E81("E81", "pebibit per square metre"),
	P_E82("E82", "pebibit per cubic metre"),
	P_E83("E83", "terabit"),
	P_E84("E84", "terabit per second"),
	P_E85("E85", "tebibit per metre"),
	P_E86("E86", "tebibit per cubic metre"),
	P_E87("E87", "tebibit per square metre"),
	P_E88("E88", "bit per metre"),
	P_E89("E89", "bit per square metre"),
	P_E90("E90", "reciprocal centimetre"),
	P_E91("E91", "reciprocal day"),
	P_E92("E92", "cubic decimetre per hour"),
	P_E93("E93", "kilogram per hour"),
	P_E94("E94", "kilomole per second"),
	P_E95("E95", "mole per second"),
	P_E96("E96", "degree per second"),
	P_E97("E97", "millimetre per degree Celcius metre"),
	P_E98("E98", "degree Celsius per kelvin"),
	P_E99("E99", "hectopascal per bar"),
	P_EA("EA", "each"),
	P_EB("EB", "electronic mail box"),
	P_EQ("EQ", "equivalent gallon"),
	P_F01("F01", "bit per cubic metre"),
	P_F02("F02", "kelvin per kelvin"),
	P_F03("F03", "kilopascal per bar"),
	P_F04("F04", "millibar per bar"),
	P_F05("F05", "megapascal per bar"),
	P_F06("F06", "poise per bar"),
	P_F07("F07", "pascal per bar"),
	P_F08("F08", "milliampere per inch"),
	P_F10("F10", "kelvin per hour"),
	P_F11("F11", "kelvin per minute"),
	P_F12("F12", "kelvin per second"),
	P_F13("F13", "slug"),
	P_F14("F14", "gram per kelvin"),
	P_F15("F15", "kilogram per kelvin"),
	P_F16("F16", "milligram per kelvin"),
	P_F17("F17", "pound-force per foot"),
	P_F18("F18", "kilogram square centimetre"),
	P_F19("F19", "kilogram square millimetre"),
	P_F20("F20", "pound inch squared"),
	P_F21("F21", "pound-force inch"),
	P_F22("F22", "pound-force foot per ampere"),
	P_F23("F23", "gram per cubic decimetre"),
	P_F24("F24", "kilogram per kilomol"),
	P_F25("F25", "gram per hertz"),
	P_F26("F26", "gram per day"),
	P_F27("F27", "gram per hour"),
	P_F28("F28", "gram per minute"),
	P_F29("F29", "gram per second"),
	P_F30("F30", "kilogram per day"),
	P_F31("F31", "kilogram per minute"),
	P_F32("F32", "milligram per day"),
	P_F33("F33", "milligram per minute"),
	P_F34("F34", "milligram per second"),
	P_F35("F35", "gram per day kelvin"),
	P_F36("F36", "gram per hour kelvin"),
	P_F37("F37", "gram per minute kelvin"),
	P_F38("F38", "gram per second kelvin"),
	P_F39("F39", "kilogram per day kelvin"),
	P_F40("F40", "kilogram per hour kelvin"),
	P_F41("F41", "kilogram per minute kelvin"),
	P_F42("F42", "kilogram per second kelvin"),
	P_F43("F43", "milligram per day kelvin"),
	P_F44("F44", "milligram per hour kelvin"),
	P_F45("F45", "milligram per minute kelvin"),
	P_F46("F46", "milligram per second kelvin"),
	P_F47("F47", "newton per millimetre"),
	P_F48("F48", "pound-force per inch"),
	P_F49("F49", "rod [unit of distance]"),
	P_F50("F50", "micrometre per kelvin"),
	P_F51("F51", "centimetre per kelvin"),
	P_F52("F52", "metre per kelvin"),
	P_F53("F53", "millimetre per kelvin"),
	P_F54("F54", "milliohm per metre"),
	P_F55("F55", "ohm per mile (statute mile)"),
	P_F56("F56", "ohm per kilometre"),
	P_F57("F57", "milliampere per pound-force per square inch"),
	P_F58("F58", "reciprocal bar"),
	P_F59("F59", "milliampere per bar"),
	P_F60("F60", "degree Celsius per bar"),
	P_F61("F61", "kelvin per bar"),
	P_F62("F62", "gram per day bar"),
	P_F63("F63", "gram per hour bar"),
	P_F64("F64", "gram per minute bar"),
	P_F65("F65", "gram per second bar"),
	P_F66("F66", "kilogram per day bar"),
	P_F67("F67", "kilogram per hour bar"),
	P_F68("F68", "kilogram per minute bar"),
	P_F69("F69", "kilogram per second bar"),
	P_F70("F70", "milligram per day bar"),
	P_F71("F71", "milligram per hour bar"),
	P_F72("F72", "milligram per minute bar"),
	P_F73("F73", "milligram per second bar"),
	P_F74("F74", "gram per bar"),
	P_F75("F75", "milligram per bar"),
	P_F76("F76", "milliampere per millimetre"),
	P_F77("F77", "pascal second per kelvin"),
	P_F78("F78", "inch of water"),
	P_F79("F79", "inch of mercury"),
	P_F80("F80", "water horse power"),
	P_F81("F81", "bar per kelvin"),
	P_F82("F82", "hectopascal per kelvin"),
	P_F83("F83", "kilopascal per kelvin"),
	P_F84("F84", "millibar per kelvin"),
	P_F85("F85", "megapascal per kelvin"),
	P_F86("F86", "poise per kelvin"),
	P_F87("F87", "volt per litre minute"),
	P_F88("F88", "newton centimetre"),
	P_F89("F89", "newton metre per degree"),
	P_F90("F90", "newton metre per ampere"),
	P_F91("F91", "bar litre per second"),
	P_F92("F92", "bar cubic metre per second"),
	P_F93("F93", "hectopascal litre per second"),
	P_F94("F94", "hectopascal cubic metre per second"),
	P_F95("F95", "millibar litre per second"),
	P_F96("F96", "millibar cubic metre per second"),
	P_F97("F97", "megapascal litre per second"),
	P_F98("F98", "megapascal cubic metre per second"),
	P_F99("F99", "pascal litre per second"),
	P_FAH("FAH", "degree Fahrenheit"),
	P_FAR("FAR", "farad"),
	P_FBM("FBM", "fibre metre"),
	P_FC("FC", "thousand cubic foot"),
	P_FF("FF", "hundred cubic metre"),
	P_FH("FH", "micromole"),
	P_FIT("FIT", "failures in time"),
	P_FL("FL", "flake ton"),
	P_FNU("FNU", "Formazin nephelometric unit"),
	P_FOT("FOT", "foot"),
	P_FP("FP", "pound per square foot"),
	P_FR("FR", "foot per minute"),
	P_FS("FS", "foot per second"),
	P_FTK("FTK", "square foot"),
	P_FTQ("FTQ", "cubic foot"),
	P_G01("G01", "pascal cubic metre per second"),
	P_G04("G04", "centimetre per bar"),
	P_G05("G05", "metre per bar"),
	P_G06("G06", "millimetre per bar"),
	P_G08("G08", "square inch per second"),
	P_G09("G09", "square metre per second kelvin"),
	P_G10("G10", "stokes per kelvin"),
	P_G11("G11", "gram per cubic centimetre bar"),
	P_G12("G12", "gram per cubic decimetre bar"),
	P_G13("G13", "gram per litre bar"),
	P_G14("G14", "gram per cubic metre bar"),
	P_G15("G15", "gram per millilitre bar"),
	P_G16("G16", "kilogram per cubic centimetre bar"),
	P_G17("G17", "kilogram per litre bar"),
	P_G18("G18", "kilogram per cubic metre bar"),
	P_G19("G19", "newton metre per kilogram"),
	P_G2("G2", "US gallon per minute"),
	P_G20("G20", "pound-force foot per pound"),
	P_G21("G21", "cup [unit of volume]"),
	P_G23("G23", "peck"),
	P_G24("G24", "tablespoon (US)"),
	P_G25("G25", "teaspoon (US)"),
	P_G26("G26", "stere"),
	P_G27("G27", "cubic centimetre per kelvin"),
	P_G28("G28", "litre per kelvin"),
	P_G29("G29", "cubic metre per kelvin"),
	P_G3("G3", "Imperial gallon per minute"),
	P_G30("G30", "millilitre per kelvin"),
	P_G31("G31", "kilogram per cubic centimetre"),
	P_G32("G32", "ounce (avoirdupois) per cubic yard"),
	P_G33("G33", "gram per cubic centimetre kelvin"),
	P_G34("G34", "gram per cubic decimetre kelvin"),
	P_G35("G35", "gram per litre kelvin"),
	P_G36("G36", "gram per cubic metre kelvin"),
	P_G37("G37", "gram per millilitre kelvin"),
	P_G38("G38", "kilogram per cubic centimetre kelvin"),
	P_G39("G39", "kilogram per litre kelvin"),
	P_G40("G40", "kilogram per cubic metre kelvin"),
	P_G41("G41", "square metre per second bar"),
	P_G42("G42", "microsiemens per centimetre"),
	P_G43("G43", "microsiemens per metre"),
	P_G44("G44", "nanosiemens per centimetre"),
	P_G45("G45", "nanosiemens per metre"),
	P_G46("G46", "stokes per bar"),
	P_G47("G47", "cubic centimetre per day"),
	P_G48("G48", "cubic centimetre per hour"),
	P_G49("G49", "cubic centimetre per minute"),
	P_G50("G50", "gallon (US) per hour"),
	P_G51("G51", "litre per second"),
	P_G52("G52", "cubic metre per day"),
	P_G53("G53", "cubic metre per minute"),
	P_G54("G54", "millilitre per day"),
	P_G55("G55", "millilitre per hour"),
	P_G56("G56", "cubic inch per hour"),
	P_G57("G57", "cubic inch per minute"),
	P_G58("G58", "cubic inch per second"),
	P_G59("G59", "milliampere per litre minute"),
	P_G60("G60", "volt per bar"),
	P_G61("G61", "cubic centimetre per day kelvin"),
	P_G62("G62", "cubic centimetre per hour kelvin"),
	P_G63("G63", "cubic centimetre per minute kelvin"),
	P_G64("G64", "cubic centimetre per second kelvin"),
	P_G65("G65", "litre per day kelvin"),
	P_G66("G66", "litre per hour kelvin"),
	P_G67("G67", "litre per minute kelvin"),
	P_G68("G68", "litre per second kelvin"),
	P_G69("G69", "cubic metre per day kelvin"),
	P_G70("G70", "cubic metre per hour kelvin"),
	P_G71("G71", "cubic metre per minute kelvin"),
	P_G72("G72", "cubic metre per second kelvin"),
	P_G73("G73", "millilitre per day kelvin"),
	P_G74("G74", "millilitre per hour kelvin"),
	P_G75("G75", "millilitre per minute kelvin"),
	P_G76("G76", "millilitre per second kelvin"),
	P_G77("G77", "millimetre to the fourth power"),
	P_G78("G78", "cubic centimetre per day bar"),
	P_G79("G79", "cubic centimetre per hour bar"),
	P_G80("G80", "cubic centimetre per minute bar"),
	P_G81("G81", "cubic centimetre per second bar"),
	P_G82("G82", "litre per day bar"),
	P_G83("G83", "litre per hour bar"),
	P_G84("G84", "litre per minute bar"),
	P_G85("G85", "litre per second bar"),
	P_G86("G86", "cubic metre per day bar"),
	P_G87("G87", "cubic metre per hour bar"),
	P_G88("G88", "cubic metre per minute bar"),
	P_G89("G89", "cubic metre per second bar"),
	P_G90("G90", "millilitre per day bar"),
	P_G91("G91", "millilitre per hour bar"),
	P_G92("G92", "millilitre per minute bar"),
	P_G93("G93", "millilitre per second bar"),
	P_G94("G94", "cubic centimetre per bar"),
	P_G95("G95", "litre per bar"),
	P_G96("G96", "cubic metre per bar"),
	P_G97("G97", "millilitre per bar"),
	P_G98("G98", "microhenry per kiloohm"),
	P_G99("G99", "microhenry per ohm"),
	P_GB("GB", "gallon (US) per day"),
	P_GBQ("GBQ", "gigabecquerel"),
	P_GDW("GDW", "gram, dry weight"),
	P_GE("GE", "pound per gallon (US)"),
	P_GF("GF", "gram per metre (gram per 100 centimetres)"),
	P_GFI("GFI", "gram of fissile isotope"),
	P_GGR("GGR", "great gross"),
	P_GIA("GIA", "gill (US)"),
	P_GIC("GIC", "gram, including container"),
	P_GII("GII", "gill (UK)"),
	P_GIP("GIP", "gram, including inner packaging"),
	P_GJ("GJ", "gram per millilitre"),
	P_GL("GL", "gram per litre"),
	P_GLD("GLD", "dry gallon (US)"),
	P_GLI("GLI", "gallon (UK)"),
	P_GLL("GLL", "gallon (US)"),
	P_GM("GM", "gram per square metre"),
	P_GO("GO", "milligram per square metre"),
	P_GP("GP", "milligram per cubic metre"),
	P_GQ("GQ", "microgram per cubic metre"),
	P_GRM("GRM", "gram"),
	P_GRN("GRN", "grain"),
	P_GRO("GRO", "gross"),
	P_GV("GV", "gigajoule"),
	P_GWH("GWH", "gigawatt hour"),
	P_H03("H03", "henry per kiloohm"),
	P_H04("H04", "henry per ohm"),
	P_H05("H05", "millihenry per kiloohm"),
	P_H06("H06", "millihenry per ohm"),
	P_H07("H07", "pascal second per bar"),
	P_H08("H08", "microbecquerel"),
	P_H09("H09", "reciprocal year"),
	P_H10("H10", "reciprocal hour"),
	P_H11("H11", "reciprocal month"),
	P_H12("H12", "degree Celsius per hour"),
	P_H13("H13", "degree Celsius per minute"),
	P_H14("H14", "degree Celsius per second"),
	P_H15("H15", "square centimetre per gram"),
	P_H16("H16", "square decametre"),
	P_H18("H18", "square hectometre"),
	P_H19("H19", "cubic hectometre"),
	P_H20("H20", "cubic kilometre"),
	P_H21("H21", "blank"),
	P_H22("H22", "volt square inch per pound-force"),
	P_H23("H23", "volt per inch"),
	P_H24("H24", "volt per microsecond"),
	P_H25("H25", "percent per kelvin"),
	P_H26("H26", "ohm per metre"),
	P_H27("H27", "degree per metre"),
	P_H28("H28", "microfarad per kilometre"),
	P_H29("H29", "microgram per litre"),
	P_H30("H30", "square micrometre (square micron)"),
	P_H31("H31", "ampere per kilogram"),
	P_H32("H32", "ampere squared second"),
	P_H33("H33", "farad per kilometre"),
	P_H34("H34", "hertz metre"),
	P_H35("H35", "kelvin metre per watt"),
	P_H36("H36", "megaohm per kilometre"),
	P_H37("H37", "megaohm per metre"),
	P_H38("H38", "megaampere"),
	P_H39("H39", "megahertz kilometre"),
	P_H40("H40", "newton per ampere"),
	P_H41("H41", "newton metre watt to the power minus 0,5"),
	P_H42("H42", "pascal per metre"),
	P_H43("H43", "siemens per centimetre"),
	P_H44("H44", "teraohm"),
	P_H45("H45", "volt second per metre"),
	P_H46("H46", "volt per second"),
	P_H47("H47", "watt per cubic metre"),
	P_H48("H48", "attofarad"),
	P_H49("H49", "centimetre per hour"),
	P_H50("H50", "reciprocal cubic centimetre"),
	P_H51("H51", "decibel per kilometre"),
	P_H52("H52", "decibel per metre"),
	P_H53("H53", "kilogram per bar"),
	P_H54("H54", "kilogram per cubic decimetre kelvin"),
	P_H55("H55", "kilogram per cubic decimetre bar"),
	P_H56("H56", "kilogram per square metre second"),
	P_H57("H57", "inch per two pi radiant"),
	P_H58("H58", "metre per volt second"),
	P_H59("H59", "square metre per newton"),
	P_H60("H60", "cubic metre per cubic metre"),
	P_H61("H61", "millisiemens per centimetre"),
	P_H62("H62", "millivolt per minute"),
	P_H63("H63", "milligram per square centimetre"),
	P_H64("H64", "milligram per gram"),
	P_H65("H65", "millilitre per cubic metre"),
	P_H66("H66", "millimetre per year"),
	P_H67("H67", "millimetre per hour"),
	P_H68("H68", "millimole per gram"),
	P_H69("H69", "picopascal per kilometre"),
	P_H70("H70", "picosecond"),
	P_H71("H71", "percent per month"),
	P_H72("H72", "percent per hectobar"),
	P_H73("H73", "percent per decakelvin"),
	P_H74("H74", "watt per metre"),
	P_H75("H75", "decapascal"),
	P_H76("H76", "gram per millimetre"),
	P_H77("H77", "module width"),
	P_H79("H79", "French gauge"),
	P_H80("H80", "rack unit"),
	P_H81("H81", "millimetre per minute"),
	P_H82("H82", "big point"),
	P_H83("H83", "litre per kilogram"),
	P_H84("H84", "gram millimetre"),
	P_H85("H85", "reciprocal week"),
	P_H87("H87", "piece"),
	P_H88("H88", "megaohm kilometre"),
	P_H89("H89", "percent per ohm"),
	P_H90("H90", "percent per degree"),
	P_H91("H91", "percent per ten thousand"),
	P_H92("H92", "percent per one hundred thousand"),
	P_H93("H93", "percent per hundred"),
	P_H94("H94", "percent per thousand"),
	P_H95("H95", "percent per volt"),
	P_H96("H96", "percent per bar"),
	P_H98("H98", "percent per inch"),
	P_H99("H99", "percent per metre"),
	P_HA("HA", "hank"),
	P_HAD("HAD", "Piece Day"),
	P_HBA("HBA", "hectobar"),
	P_HBX("HBX", "hundred boxes"),
	P_HC("HC", "hundred count"),
	P_HDW("HDW", "hundred kilogram, dry weight"),
	P_HEA("HEA", "head"),
	P_HGM("HGM", "hectogram"),
	P_HH("HH", "hundred cubic foot"),
	P_HIU("HIU", "hundred international unit"),
	P_HKM("HKM", "hundred kilogram, net mass"),
	P_HLT("HLT", "hectolitre"),
	P_HM("HM", "mile per hour (statute mile)"),
	P_HMO("HMO", "Piece Month"),
	P_HMQ("HMQ", "million cubic metre"),
	P_HMT("HMT", "hectometre"),
	P_HPA("HPA", "hectolitre of pure alcohol"),
	P_HTZ("HTZ", "hertz"),
	P_HUR("HUR", "hour"),
	P_IA("IA", "inch pound (pound inch)"),
	P_IE("IE", "person"),
	P_INH("INH", "inch"),
	P_INK("INK", "square inch"),
	P_INQ("INQ", "cubic inch"),
	P_ISD("ISD", "international sugar degree"),
	P_IU("IU", "inch per second"),
	P_IUG("IUG", "international unit per gram"),
	P_IV("IV", "inch per second squared"),
	P_J10("J10", "percent per millimetre"),
	P_J12("J12", "per mille per psi"),
	P_J13("J13", "degree API"),
	P_J14("J14", "degree Baume (origin scale)"),
	P_J15("J15", "degree Baume (US heavy)"),
	P_J16("J16", "degree Baume (US light)"),
	P_J17("J17", "degree Balling"),
	P_J18("J18", "degree Brix"),
	P_J19("J19", "degree Fahrenheit hour square foot per British thermal unit (thermochemical)"),
	P_J2("J2", "joule per kilogram"),
	P_J20("J20", "degree Fahrenheit per kelvin"),
	P_J21("J21", "degree Fahrenheit per bar"),
	P_J22("J22", "degree Fahrenheit hour square foot per British thermal unit (international table)"),
	P_J23("J23", "degree Fahrenheit per hour"),
	P_J24("J24", "degree Fahrenheit per minute"),
	P_J25("J25", "degree Fahrenheit per second"),
	P_J26("J26", "reciprocal degree Fahrenheit"),
	P_J27("J27", "degree Oechsle"),
	P_J28("J28", "degree Rankine per hour"),
	P_J29("J29", "degree Rankine per minute"),
	P_J30("J30", "degree Rankine per second"),
	P_J31("J31", "degree Twaddell"),
	P_J32("J32", "micropoise"),
	P_J33("J33", "microgram per kilogram"),
	P_J34("J34", "microgram per cubic metre kelvin"),
	P_J35("J35", "microgram per cubic metre bar"),
	P_J36("J36", "microlitre per litre"),
	P_J38("J38", "baud"),
	P_J39("J39", "British thermal unit (mean)"),
	P_J40("J40", "British thermal unit (international table) foot per hour square foot degree Fahrenheit"),
	P_J41("J41", "British thermal unit (international table) inch per hour square foot degree Fahrenheit"),
	P_J42("J42", "British thermal unit (international table) inch per second square foot degree Fahrenheit"),
	P_J43("J43", "British thermal unit (international table) per pound degree Fahrenheit"),
	P_J44("J44", "British thermal unit (international table) per minute"),
	P_J45("J45", "British thermal unit (international table) per second"),
	P_J46("J46", "British thermal unit (thermochemical) foot per hour square foot degree Fahrenheit"),
	P_J47("J47", "British thermal unit (thermochemical) per hour"),
	P_J48("J48", "British thermal unit (thermochemical) inch per hour square foot degree Fahrenheit"),
	P_J49("J49", "British thermal unit (thermochemical) inch per second square foot degree Fahrenheit"),
	P_J50("J50", "British thermal unit (thermochemical) per pound degree Fahrenheit"),
	P_J51("J51", "British thermal unit (thermochemical) per minute"),
	P_J52("J52", "British thermal unit (thermochemical) per second"),
	P_J53("J53", "coulomb square metre per kilogram"),
	P_J54("J54", "megabaud"),
	P_J55("J55", "watt second"),
	P_J56("J56", "bar per bar"),
	P_J57("J57", "barrel (UK petroleum)"),
	P_J58("J58", "barrel (UK petroleum) per minute"),
	P_J59("J59", "barrel (UK petroleum) per day"),
	P_J60("J60", "barrel (UK petroleum) per hour"),
	P_J61("J61", "barrel (UK petroleum) per second"),
	P_J62("J62", "barrel (US petroleum) per hour"),
	P_J63("J63", "barrel (US petroleum) per second"),
	P_J64("J64", "bushel (UK) per day"),
	P_J65("J65", "bushel (UK) per hour"),
	P_J66("J66", "bushel (UK) per minute"),
	P_J67("J67", "bushel (UK) per second"),
	P_J68("J68", "bushel (US dry) per day"),
	P_J69("J69", "bushel (US dry) per hour"),
	P_J70("J70", "bushel (US dry) per minute"),
	P_J71("J71", "bushel (US dry) per second"),
	P_J72("J72", "centinewton metre"),
	P_J73("J73", "centipoise per kelvin"),
	P_J74("J74", "centipoise per bar"),
	P_J75("J75", "calorie (mean)"),
	P_J76("J76", "calorie (international table) per gram degree Celsius"),
	P_J78("J78", "calorie (thermochemical) per centimetre second degree Celsius"),
	P_J79("J79", "calorie (thermochemical) per gram degree Celsius"),
	P_J81("J81", "calorie (thermochemical) per minute"),
	P_J82("J82", "calorie (thermochemical) per second"),
	P_J83("J83", "clo"),
	P_J84("J84", "centimetre per second kelvin"),
	P_J85("J85", "centimetre per second bar"),
	P_J87("J87", "cubic centimetre per cubic metre"),
	P_J90("J90", "cubic decimetre per day"),
	P_J91("J91", "cubic decimetre per cubic metre"),
	P_J92("J92", "cubic decimetre per minute"),
	P_J93("J93", "cubic decimetre per second"),
	P_J95("J95", "ounce (UK fluid) per day"),
	P_J96("J96", "ounce (UK fluid) per hour"),
	P_J97("J97", "ounce (UK fluid) per minute"),
	P_J98("J98", "ounce (UK fluid) per second"),
	P_J99("J99", "ounce (US fluid) per day"),
	P_JE("JE", "joule per kelvin"),
	P_JK("JK", "megajoule per kilogram"),
	P_JM("JM", "megajoule per cubic metre"),
	P_JNT("JNT", "pipeline joint"),
	P_JOU("JOU", "joule"),
	P_JPS("JPS", "hundred metre"),
	P_JWL("JWL", "number of jewels"),
	P_K1("K1", "kilowatt demand"),
	P_K10("K10", "ounce (US fluid) per hour"),
	P_K11("K11", "ounce (US fluid) per minute"),
	P_K12("K12", "ounce (US fluid) per second"),
	P_K13("K13", "foot per degree Fahrenheit"),
	P_K14("K14", "foot per hour"),
	P_K15("K15", "foot pound-force per hour"),
	P_K16("K16", "foot pound-force per minute"),
	P_K17("K17", "foot per psi"),
	P_K18("K18", "foot per second degree Fahrenheit"),
	P_K19("K19", "foot per second psi"),
	P_K2("K2", "kilovolt ampere reactive demand"),
	P_K20("K20", "reciprocal cubic foot"),
	P_K21("K21", "cubic foot per degree Fahrenheit"),
	P_K22("K22", "cubic foot per day"),
	P_K23("K23", "cubic foot per psi"),
	P_K26("K26", "gallon (UK) per day"),
	P_K27("K27", "gallon (UK) per hour"),
	P_K28("K28", "gallon (UK) per second"),
	P_K3("K3", "kilovolt ampere reactive hour"),
	P_K30("K30", "gallon (US liquid) per second"),
	P_K31("K31", "gram-force per square centimetre"),
	P_K32("K32", "gill (UK) per day"),
	P_K33("K33", "gill (UK) per hour"),
	P_K34("K34", "gill (UK) per minute"),
	P_K35("K35", "gill (UK) per second"),
	P_K36("K36", "gill (US) per day"),
	P_K37("K37", "gill (US) per hour"),
	P_K38("K38", "gill (US) per minute"),
	P_K39("K39", "gill (US) per second"),
	P_K40("K40", "standard acceleration of free fall"),
	P_K41("K41", "grain per gallon (US)"),
	P_K42("K42", "horsepower (boiler)"),
	P_K43("K43", "horsepower (electric)"),
	P_K45("K45", "inch per degree Fahrenheit"),
	P_K46("K46", "inch per psi"),
	P_K47("K47", "inch per second degree Fahrenheit"),
	P_K48("K48", "inch per second psi"),
	P_K49("K49", "reciprocal cubic inch"),
	P_K50("K50", "kilobaud"),
	P_K51("K51", "kilocalorie (mean)"),
	P_K52("K52", "kilocalorie (international table) per hour metre degree Celsius"),
	P_K53("K53", "kilocalorie (thermochemical)"),
	P_K54("K54", "kilocalorie (thermochemical) per minute"),
	P_K55("K55", "kilocalorie (thermochemical) per second"),
	P_K58("K58", "kilomole per hour"),
	P_K59("K59", "kilomole per cubic metre kelvin"),
	P_K6("K6", "kilolitre"),
	P_K60("K60", "kilomole per cubic metre bar"),
	P_K61("K61", "kilomole per minute"),
	P_K62("K62", "litre per litre"),
	P_K63("K63", "reciprocal litre"),
	P_K64("K64", "pound (avoirdupois) per degree Fahrenheit"),
	P_K65("K65", "pound (avoirdupois) square foot"),
	P_K66("K66", "pound (avoirdupois) per day"),
	P_K67("K67", "pound per foot hour"),
	P_K68("K68", "pound per foot second"),
	P_K69("K69", "pound (avoirdupois) per cubic foot degree Fahrenheit"),
	P_K70("K70", "pound (avoirdupois) per cubic foot psi"),
	P_K71("K71", "pound (avoirdupois) per gallon (UK)"),
	P_K73("K73", "pound (avoirdupois) per hour degree Fahrenheit"),
	P_K74("K74", "pound (avoirdupois) per hour psi"),
	P_K75("K75", "pound (avoirdupois) per cubic inch degree Fahrenheit"),
	P_K76("K76", "pound (avoirdupois) per cubic inch psi"),
	P_K77("K77", "pound (avoirdupois) per psi"),
	P_K78("K78", "pound (avoirdupois) per minute"),
	P_K79("K79", "pound (avoirdupois) per minute degree Fahrenheit"),
	P_K80("K80", "pound (avoirdupois) per minute psi"),
	P_K81("K81", "pound (avoirdupois) per second"),
	P_K82("K82", "pound (avoirdupois) per second degree Fahrenheit"),
	P_K83("K83", "pound (avoirdupois) per second psi"),
	P_K84("K84", "pound per cubic yard"),
	P_K85("K85", "pound-force per square foot"),
	P_K86("K86", "pound-force per square inch degree Fahrenheit"),
	P_K87("K87", "psi cubic inch per second"),
	P_K88("K88", "psi litre per second"),
	P_K89("K89", "psi cubic metre per second"),
	P_K90("K90", "psi cubic yard per second"),
	P_K91("K91", "pound-force second per square foot"),
	P_K92("K92", "pound-force second per square inch"),
	P_K93("K93", "reciprocal psi"),
	P_K94("K94", "quart (UK liquid) per day"),
	P_K95("K95", "quart (UK liquid) per hour"),
	P_K96("K96", "quart (UK liquid) per minute"),
	P_K97("K97", "quart (UK liquid) per second"),
	P_K98("K98", "quart (US liquid) per day"),
	P_K99("K99", "quart (US liquid) per hour"),
	P_KA("KA", "cake"),
	P_KAT("KAT", "katal"),
	P_KB("KB", "kilocharacter"),
	P_KBA("KBA", "kilobar"),
	P_KCC("KCC", "kilogram of choline chloride"),
	P_KDW("KDW", "kilogram drained net weight"),
	P_KEL("KEL", "kelvin"),
	P_KGM("KGM", "kilogram"),
	P_KGS("KGS", "kilogram per second"),
	P_KHY("KHY", "kilogram of hydrogen peroxide"),
	P_KHZ("KHZ", "kilohertz"),
	P_KI("KI", "kilogram per millimetre width"),
	P_KIC("KIC", "kilogram, including container"),
	P_KIP("KIP", "kilogram, including inner packaging"),
	P_KJ("KJ", "kilosegment"),
	P_KJO("KJO", "kilojoule"),
	P_KL("KL", "kilogram per metre"),
	P_KLK("KLK", "lactic dry material percentage"),
	P_KLX("KLX", "kilolux"),
	P_KMA("KMA", "kilogram of methylamine"),
	P_KMH("KMH", "kilometre per hour"),
	P_KMK("KMK", "square kilometre"),
	P_KMQ("KMQ", "kilogram per cubic metre"),
	P_KMT("KMT", "kilometre"),
	P_KNI("KNI", "kilogram of nitrogen"),
	P_KNM("KNM", "kilonewton per square metre"),
	P_KNS("KNS", "kilogram named substance"),
	P_KNT("KNT", "knot"),
	P_KO("KO", "milliequivalence caustic potash per gram of product"),
	P_KPA("KPA", "kilopascal"),
	P_KPH("KPH", "kilogram of potassium hydroxide (caustic potash)"),
	P_KPO("KPO", "kilogram of potassium oxide"),
	P_KPP("KPP", "kilogram of phosphorus pentoxide (phosphoric anhydride)"),
	P_KR("KR", "kiloroentgen"),
	P_KSD("KSD", "kilogram of substance 90 % dry"),
	P_KSH("KSH", "kilogram of sodium hydroxide (caustic soda)"),
	P_KT("KT", "kit"),
	P_KTN("KTN", "kilotonne"),
	P_KUR("KUR", "kilogram of uranium"),
	P_KVA("KVA", "kilovolt - ampere"),
	P_KVR("KVR", "kilovar"),
	P_KVT("KVT", "kilovolt"),
	P_KW("KW", "kilogram per millimetre"),
	P_KWH("KWH", "kilowatt hour"),
	P_KWN("KWN", "Kilowatt hour per normalized cubic metre"),
	P_KWO("KWO", "kilogram of tungsten trioxide"),
	P_KWS("KWS", "Kilowatt hour per standard cubic metre"),
	P_KWT("KWT", "kilowatt"),
	P_KWY("KWY", "kilowatt year"),
	P_KX("KX", "millilitre per kilogram"),
	P_L10("L10", "quart (US liquid) per minute"),
	P_L11("L11", "quart (US liquid) per second"),
	P_L12("L12", "metre per second kelvin"),
	P_L13("L13", "metre per second bar"),
	P_L14("L14", "square metre hour degree Celsius per kilocalorie (international table)"),
	P_L15("L15", "millipascal second per kelvin"),
	P_L16("L16", "millipascal second per bar"),
	P_L17("L17", "milligram per cubic metre kelvin"),
	P_L18("L18", "milligram per cubic metre bar"),
	P_L19("L19", "millilitre per litre"),
	P_L2("L2", "litre per minute"),
	P_L20("L20", "reciprocal cubic millimetre"),
	P_L21("L21", "cubic millimetre per cubic metre"),
	P_L23("L23", "mole per hour"),
	P_L24("L24", "mole per kilogram kelvin"),
	P_L25("L25", "mole per kilogram bar"),
	P_L26("L26", "mole per litre kelvin"),
	P_L27("L27", "mole per litre bar"),
	P_L28("L28", "mole per cubic metre kelvin"),
	P_L29("L29", "mole per cubic metre bar"),
	P_L30("L30", "mole per minute"),
	P_L31("L31", "milliroentgen aequivalent men"),
	P_L32("L32", "nanogram per kilogram"),
	P_L33("L33", "ounce (avoirdupois) per day"),
	P_L34("L34", "ounce (avoirdupois) per hour"),
	P_L35("L35", "ounce (avoirdupois) per minute"),
	P_L36("L36", "ounce (avoirdupois) per second"),
	P_L37("L37", "ounce (avoirdupois) per gallon (UK)"),
	P_L38("L38", "ounce (avoirdupois) per gallon (US)"),
	P_L39("L39", "ounce (avoirdupois) per cubic inch"),
	P_L40("L40", "ounce (avoirdupois)-force"),
	P_L41("L41", "ounce (avoirdupois)-force inch"),
	P_L42("L42", "picosiemens per metre"),
	P_L43("L43", "peck (UK)"),
	P_L44("L44", "peck (UK) per day"),
	P_L45("L45", "peck (UK) per hour"),
	P_L46("L46", "peck (UK) per minute"),
	P_L47("L47", "peck (UK) per second"),
	P_L48("L48", "peck (US dry) per day"),
	P_L49("L49", "peck (US dry) per hour"),
	P_L50("L50", "peck (US dry) per minute"),
	P_L51("L51", "peck (US dry) per second"),
	P_L52("L52", "psi per psi"),
	P_L53("L53", "pint (UK) per day"),
	P_L54("L54", "pint (UK) per hour"),
	P_L55("L55", "pint (UK) per minute"),
	P_L56("L56", "pint (UK) per second"),
	P_L57("L57", "pint (US liquid) per day"),
	P_L58("L58", "pint (US liquid) per hour"),
	P_L59("L59", "pint (US liquid) per minute"),
	P_L60("L60", "pint (US liquid) per second"),
	P_L63("L63", "slug per day"),
	P_L64("L64", "slug per foot second"),
	P_L65("L65", "slug per cubic foot"),
	P_L66("L66", "slug per hour"),
	P_L67("L67", "slug per minute"),
	P_L68("L68", "slug per second"),
	P_L69("L69", "tonne per kelvin"),
	P_L70("L70", "tonne per bar"),
	P_L71("L71", "tonne per day"),
	P_L72("L72", "tonne per day kelvin"),
	P_L73("L73", "tonne per day bar"),
	P_L74("L74", "tonne per hour kelvin"),
	P_L75("L75", "tonne per hour bar"),
	P_L76("L76", "tonne per cubic metre kelvin"),
	P_L77("L77", "tonne per cubic metre bar"),
	P_L78("L78", "tonne per minute"),
	P_L79("L79", "tonne per minute kelvin"),
	P_L80("L80", "tonne per minute bar"),
	P_L81("L81", "tonne per second"),
	P_L82("L82", "tonne per second kelvin"),
	P_L83("L83", "tonne per second bar"),
	P_L84("L84", "ton (UK shipping)"),
	P_L85("L85", "ton long per day"),
	P_L86("L86", "ton (US shipping)"),
	P_L87("L87", "ton short per degree Fahrenheit"),
	P_L88("L88", "ton short per day"),
	P_L89("L89", "ton short per hour degree Fahrenheit"),
	P_L90("L90", "ton short per hour psi"),
	P_L91("L91", "ton short per psi"),
	P_L92("L92", "ton (UK long) per cubic yard"),
	P_L93("L93", "ton (US short) per cubic yard"),
	P_L94("L94", "ton-force (US short)"),
	P_L95("L95", "common year"),
	P_L96("L96", "sidereal year"),
	P_L98("L98", "yard per degree Fahrenheit"),
	P_L99("L99", "yard per psi"),
	P_LA("LA", "pound per cubic inch"),
	P_LAC("LAC", "lactose excess percentage"),
	P_LBR("LBR", "pound"),
	P_LBT("LBT", "troy pound (US)"),
	P_LD("LD", "litre per day"),
	P_LEF("LEF", "leaf"),
	P_LF("LF", "linear foot"),
	P_LH("LH", "labour hour"),
	P_LK("LK", "link"),
	P_LM("LM", "linear metre"),
	P_LN("LN", "length"),
	P_LO("LO", "lot [unit of procurement]"),
	P_LP("LP", "liquid pound"),
	P_LPA("LPA", "litre of pure alcohol"),
	P_LR("LR", "layer"),
	P_LS("LS", "lump sum"),
	P_LTN("LTN", "ton (UK) or long ton (US)"),
	P_LTR("LTR", "litre"),
	P_LUB("LUB", "metric ton, lubricating oil"),
	P_LUM("LUM", "lumen"),
	P_LUX("LUX", "lux"),
	P_LY("LY", "linear yard"),
	P_M1("M1", "milligram per litre"),
	P_M10("M10", "reciprocal cubic yard"),
	P_M11("M11", "cubic yard per degree Fahrenheit"),
	P_M12("M12", "cubic yard per day"),
	P_M13("M13", "cubic yard per hour"),
	P_M14("M14", "cubic yard per psi"),
	P_M15("M15", "cubic yard per minute"),
	P_M16("M16", "cubic yard per second"),
	P_M17("M17", "kilohertz metre"),
	P_M18("M18", "gigahertz metre"),
	P_M19("M19", "Beaufort"),
	P_M20("M20", "reciprocal megakelvin or megakelvin to the power minus one"),
	P_M21("M21", "reciprocal kilovolt - ampere reciprocal hour"),
	P_M22("M22", "millilitre per square centimetre minute"),
	P_M23("M23", "newton per centimetre"),
	P_M24("M24", "ohm kilometre"),
	P_M25("M25", "percent per degree Celsius"),
	P_M26("M26", "gigaohm per metre"),
	P_M27("M27", "megahertz metre"),
	P_M29("M29", "kilogram per kilogram"),
	P_M30("M30", "reciprocal volt - ampere reciprocal second"),
	P_M31("M31", "kilogram per kilometre"),
	P_M32("M32", "pascal second per litre"),
	P_M33("M33", "millimole per litre"),
	P_M34("M34", "newton metre per square metre"),
	P_M35("M35", "millivolt - ampere"),
	P_M36("M36", "30-day month"),
	P_M37("M37", "actual/360"),
	P_M38("M38", "kilometre per second squared"),
	P_M39("M39", "centimetre per second squared"),
	P_M4("M4", "monetary value"),
	P_M40("M40", "yard per second squared"),
	P_M41("M41", "millimetre per second squared"),
	P_M42("M42", "mile (statute mile) per second squared"),
	P_M43("M43", "mil"),
	P_M44("M44", "revolution"),
	P_M45("M45", "degree [unit of angle] per second squared"),
	P_M46("M46", "revolution per minute"),
	P_M47("M47", "circular mil"),
	P_M48("M48", "square mile (based on U.S. survey foot)"),
	P_M49("M49", "chain (based on U.S. survey foot)"),
	P_M5("M5", "microcurie"),
	P_M50("M50", "furlong"),
	P_M51("M51", "foot (U.S. survey)"),
	P_M52("M52", "mile (based on U.S. survey foot)"),
	P_M53("M53", "metre per pascal"),
	P_M55("M55", "metre per radiant"),
	P_M56("M56", "shake"),
	P_M57("M57", "mile per minute"),
	P_M58("M58", "mile per second"),
	P_M59("M59", "metre per second pascal"),
	P_M60("M60", "metre per hour"),
	P_M61("M61", "inch per year"),
	P_M62("M62", "kilometre per second"),
	P_M63("M63", "inch per minute"),
	P_M64("M64", "yard per second"),
	P_M65("M65", "yard per minute"),
	P_M66("M66", "yard per hour"),
	P_M67("M67", "acre-foot (based on U.S. survey foot)"),
	P_M68("M68", "cord (128 ft3)"),
	P_M69("M69", "cubic mile (UK statute)"),
	P_M7("M7", "micro-inch"),
	P_M70("M70", "ton, register"),
	P_M71("M71", "cubic metre per pascal"),
	P_M72("M72", "bel"),
	P_M73("M73", "kilogram per cubic metre pascal"),
	P_M74("M74", "kilogram per pascal"),
	P_M75("M75", "kilopound-force"),
	P_M76("M76", "poundal"),
	P_M77("M77", "kilogram metre per second squared"),
	P_M78("M78", "pond"),
	P_M79("M79", "square foot per hour"),
	P_M80("M80", "stokes per pascal"),
	P_M81("M81", "square centimetre per second"),
	P_M82("M82", "square metre per second pascal"),
	P_M83("M83", "denier"),
	P_M84("M84", "pound per yard"),
	P_M85("M85", "ton, assay"),
	P_M86("M86", "pfund"),
	P_M87("M87", "kilogram per second pascal"),
	P_M88("M88", "tonne per month"),
	P_M89("M89", "tonne per year"),
	P_M9("M9", "million Btu per 1000 cubic foot"),
	P_M90("M90", "kilopound per hour"),
	P_M91("M91", "pound per pound"),
	P_M92("M92", "pound-force foot"),
	P_M93("M93", "newton metre per radian"),
	P_M94("M94", "kilogram metre"),
	P_M95("M95", "poundal foot"),
	P_M96("M96", "poundal inch"),
	P_M97("M97", "dyne metre"),
	P_M98("M98", "kilogram centimetre per second"),
	P_M99("M99", "gram centimetre per second"),
	P_MAH("MAH", "megavolt ampere reactive hour"),
	P_MAL("MAL", "megalitre"),
	P_MAM("MAM", "megametre"),
	P_MAR("MAR", "megavar"),
	P_MAW("MAW", "megawatt"),
	P_MBE("MBE", "thousand standard brick equivalent"),
	P_MBF("MBF", "thousand board foot"),
	P_MBR("MBR", "millibar"),
	P_MC("MC", "microgram"),
	P_MCU("MCU", "millicurie"),
	P_MD("MD", "air dry metric ton"),
	P_MGM("MGM", "milligram"),
	P_MHZ("MHZ", "megahertz"),
	P_MIK("MIK", "square mile (statute mile)"),
	P_MIL("MIL", "thousand"),
	P_MIN("MIN", "minute [unit of time]"),
	P_MIO("MIO", "million"),
	P_MIU("MIU", "million international unit"),
	P_MKD("MKD", "Square Metre Day"),
	P_MKM("MKM", "Square Metre Month"),
	P_MKW("MKW", "Square Metre Week"),
	P_MLD("MLD", "milliard"),
	P_MLT("MLT", "millilitre"),
	P_MMK("MMK", "square millimetre"),
	P_MMQ("MMQ", "cubic millimetre"),
	P_MMT("MMT", "millimetre"),
	P_MND("MND", "kilogram, dry weight"),
	P_MNJ("MNJ", "Mega Joule per Normalised cubic Metre"),
	P_MON("MON", "month"),
	P_MPA("MPA", "megapascal"),
	P_MQD("MQD", "Cubic Metre Day"),
	P_MQH("MQH", "cubic metre per hour"),
	P_MQM("MQM", "Cubic Metre Month"),
	P_MQS("MQS", "cubic metre per second"),
	P_MQW("MQW", "Cubic Metre Week"),
	P_MRD("MRD", "Metre Day"),
	P_MRM("MRM", "Metre Month"),
	P_MRW("MRW", "Metre Week"),
	P_MSK("MSK", "metre per second squared"),
	P_MTK("MTK", "square metre"),
	P_MTQ("MTQ", "cubic metre"),
	P_MTR("MTR", "metre"),
	P_MTS("MTS", "metre per second"),
	P_MTZ("MTZ", "milihertz"),
	P_MVA("MVA", "megavolt - ampere"),
	P_MWH("MWH", "megawatt hour (1000 kW.h)"),
	P_N1("N1", "pen calorie"),
	P_N10("N10", "pound foot per second"),
	P_N11("N11", "pound inch per second"),
	P_N12("N12", "Pferdestaerke"),
	P_N13("N13", "centimetre of mercury (0 ºC)"),
	P_N14("N14", "centimetre of water (4 ºC)"),
	P_N15("N15", "foot of water (39.2 ºF)"),
	P_N16("N16", "inch of mercury (32 ºF)"),
	P_N17("N17", "inch of mercury (60 ºF)"),
	P_N18("N18", "inch of water (39.2 ºF)"),
	P_N19("N19", "inch of water (60 ºF)"),
	P_N20("N20", "kip per square inch"),
	P_N21("N21", "poundal per square foot"),
	P_N22("N22", "ounce (avoirdupois) per square inch"),
	P_N23("N23", "conventional metre of water"),
	P_N24("N24", "gram per square millimetre"),
	P_N25("N25", "pound per square yard"),
	P_N26("N26", "poundal per square inch"),
	P_N27("N27", "foot to the fourth power"),
	P_N28("N28", "cubic decimetre per kilogram"),
	P_N29("N29", "cubic foot per pound"),
	P_N3("N3", "print point"),
	P_N30("N30", "cubic inch per pound"),
	P_N31("N31", "kilonewton per metre"),
	P_N32("N32", "poundal per inch"),
	P_N33("N33", "pound-force per yard"),
	P_N34("N34", "poundal second per square foot"),
	P_N35("N35", "poise per pascal"),
	P_N36("N36", "newton second per square metre"),
	P_N37("N37", "kilogram per metre second"),
	P_N38("N38", "kilogram per metre minute"),
	P_N39("N39", "kilogram per metre day"),
	P_N40("N40", "kilogram per metre hour"),
	P_N41("N41", "gram per centimetre second"),
	P_N42("N42", "poundal second per square inch"),
	P_N43("N43", "pound per foot minute"),
	P_N44("N44", "pound per foot day"),
	P_N45("N45", "cubic metre per second pascal"),
	P_N46("N46", "foot poundal"),
	P_N47("N47", "inch poundal"),
	P_N48("N48", "watt per square centimetre"),
	P_N49("N49", "watt per square inch"),
	P_N50("N50", "British thermal unit (international table) per square foot hour"),
	P_N51("N51", "British thermal unit (thermochemical) per square foot hour"),
	P_N52("N52", "British thermal unit (thermochemical) per square foot minute"),
	P_N53("N53", "British thermal unit (international table) per square foot second"),
	P_N54("N54", "British thermal unit (thermochemical) per square foot second"),
	P_N55("N55", "British thermal unit (international table) per square inch second"),
	P_N56("N56", "calorie (thermochemical) per square centimetre minute"),
	P_N57("N57", "calorie (thermochemical) per square centimetre second"),
	P_N58("N58", "British thermal unit (international table) per cubic foot"),
	P_N59("N59", "British thermal unit (thermochemical) per cubic foot"),
	P_N60("N60", "British thermal unit (international table) per degree Fahrenheit"),
	P_N61("N61", "British thermal unit (thermochemical) per degree Fahrenheit"),
	P_N62("N62", "British thermal unit (international table) per degree Rankine"),
	P_N63("N63", "British thermal unit (thermochemical) per degree Rankine"),
	P_N64("N64", "British thermal unit (thermochemical) per pound degree Rankine"),
	P_N65("N65", "kilocalorie (international table) per gram kelvin"),
	P_N66("N66", "British thermal unit (39 ºF)"),
	P_N67("N67", "British thermal unit (59 ºF)"),
	P_N68("N68", "British thermal unit (60 ºF)"),
	P_N69("N69", "calorie (20 ºC)"),
	P_N70("N70", "quad (1015 BtuIT)"),
	P_N71("N71", "therm (EC)"),
	P_N72("N72", "therm (U.S.)"),
	P_N73("N73", "British thermal unit (thermochemical) per pound"),
	P_N74("N74", "British thermal unit (international table) per hour square foot degree Fahrenheit"),
	P_N75("N75", "British thermal unit (thermochemical) per hour square foot degree Fahrenheit"),
	P_N76("N76", "British thermal unit (international table) per second square foot degree Fahrenheit"),
	P_N77("N77", "British thermal unit (thermochemical) per second square foot degree Fahrenheit"),
	P_N78("N78", "kilowatt per square metre kelvin"),
	P_N79("N79", "kelvin per pascal"),
	P_N80("N80", "watt per metre degree Celsius"),
	P_N81("N81", "kilowatt per metre kelvin"),
	P_N82("N82", "kilowatt per metre degree Celsius"),
	P_N83("N83", "metre per degree Celcius metre"),
	P_N84("N84", "degree Fahrenheit hour per British thermal unit (international table)"),
	P_N85("N85", "degree Fahrenheit hour per British thermal unit (thermochemical)"),
	P_N86("N86", "degree Fahrenheit second per British thermal unit (international table)"),
	P_N87("N87", "degree Fahrenheit second per British thermal unit (thermochemical)"),
	P_N88("N88", "degree Fahrenheit hour square foot per British thermal unit (international table) inch"),
	P_N89("N89", "degree Fahrenheit hour square foot per British thermal unit (thermochemical) inch"),
	P_N90("N90", "kilofarad"),
	P_N91("N91", "reciprocal joule"),
	P_N92("N92", "picosiemens"),
	P_N93("N93", "ampere per pascal"),
	P_N94("N94", "franklin"),
	P_N95("N95", "ampere minute"),
	P_N96("N96", "biot"),
	P_N97("N97", "gilbert"),
	P_N98("N98", "volt per pascal"),
	P_N99("N99", "picovolt"),
	P_NA("NA", "milligram per kilogram"),
	P_NAR("NAR", "number of articles"),
	P_NCL("NCL", "number of cells"),
	P_NEW("NEW", "newton"),
	P_NF("NF", "message"),
	P_NIL("NIL", "nil"),
	P_NIU("NIU", "number of international units"),
	P_NL("NL", "load"),
	P_NM3("NM3", "Normalised cubic metre"),
	P_NMI("NMI", "nautical mile"),
	P_NMP("NMP", "number of packs"),
	P_NPT("NPT", "number of parts"),
	P_NT("NT", "net ton"),
	P_NTU("NTU", "Nephelometric turbidity unit"),
	P_NU("NU", "newton metre"),
	P_NX("NX", "part per thousand"),
	P_OA("OA", "panel"),
	P_ODE("ODE", "ozone depletion equivalent"),
	P_ODG("ODG", "ODS Grams"),
	P_ODK("ODK", "ODS Kilograms"),
	P_ODM("ODM", "ODS Milligrams"),
	P_OHM("OHM", "ohm"),
	P_ON("ON", "ounce per square yard"),
	P_ONZ("ONZ", "ounce (avoirdupois)"),
	P_OPM("OPM", "oscillations per minute"),
	P_OT("OT", "overtime hour"),
	P_OZA("OZA", "fluid ounce (US)"),
	P_OZI("OZI", "fluid ounce (UK)"),
	P_P1("P1", "percent"),
	P_P10("P10", "coulomb per metre"),
	P_P11("P11", "kiloweber"),
	P_P12("P12", "gamma"),
	P_P13("P13", "kilotesla"),
	P_P14("P14", "joule per second"),
	P_P15("P15", "joule per minute"),
	P_P16("P16", "joule per hour"),
	P_P17("P17", "joule per day"),
	P_P18("P18", "kilojoule per second"),
	P_P19("P19", "kilojoule per minute"),
	P_P2("P2", "pound per foot"),
	P_P20("P20", "kilojoule per hour"),
	P_P21("P21", "kilojoule per day"),
	P_P22("P22", "nanoohm"),
	P_P23("P23", "ohm circular-mil per foot"),
	P_P24("P24", "kilohenry"),
	P_P25("P25", "lumen per square foot"),
	P_P26("P26", "phot"),
	P_P27("P27", "footcandle"),
	P_P28("P28", "candela per square inch"),
	P_P29("P29", "footlambert"),
	P_P30("P30", "lambert"),
	P_P31("P31", "stilb"),
	P_P32("P32", "candela per square foot"),
	P_P33("P33", "kilocandela"),
	P_P34("P34", "millicandela"),
	P_P35("P35", "Hefner-Kerze"),
	P_P36("P36", "international candle"),
	P_P37("P37", "British thermal unit (international table) per square foot"),
	P_P38("P38", "British thermal unit (thermochemical) per square foot"),
	P_P39("P39", "calorie (thermochemical) per square centimetre"),
	P_P40("P40", "langley"),
	P_P41("P41", "decade (logarithmic)"),
	P_P42("P42", "pascal squared second"),
	P_P43("P43", "bel per metre"),
	P_P44("P44", "pound mole"),
	P_P45("P45", "pound mole per second"),
	P_P46("P46", "pound mole per minute"),
	P_P47("P47", "kilomole per kilogram"),
	P_P48("P48", "pound mole per pound"),
	P_P49("P49", "newton square metre per ampere"),
	P_P5("P5", "five pack"),
	P_P50("P50", "weber metre"),
	P_P51("P51", "mol per kilogram pascal"),
	P_P52("P52", "mol per cubic metre pascal"),
	P_P53("P53", "unit pole"),
	P_P54("P54", "milligray per second"),
	P_P55("P55", "microgray per second"),
	P_P56("P56", "nanogray per second"),
	P_P57("P57", "gray per minute"),
	P_P58("P58", "milligray per minute"),
	P_P59("P59", "microgray per minute"),
	P_P60("P60", "nanogray per minute"),
	P_P61("P61", "gray per hour"),
	P_P62("P62", "milligray per hour"),
	P_P63("P63", "microgray per hour"),
	P_P64("P64", "nanogray per hour"),
	P_P65("P65", "sievert per second"),
	P_P66("P66", "millisievert per second"),
	P_P67("P67", "microsievert per second"),
	P_P68("P68", "nanosievert per second"),
	P_P69("P69", "rem per second"),
	P_P70("P70", "sievert per hour"),
	P_P71("P71", "millisievert per hour"),
	P_P72("P72", "microsievert per hour"),
	P_P73("P73", "nanosievert per hour"),
	P_P74("P74", "sievert per minute"),
	P_P75("P75", "millisievert per minute"),
	P_P76("P76", "microsievert per minute"),
	P_P77("P77", "nanosievert per minute"),
	P_P78("P78", "reciprocal square inch"),
	P_P79("P79", "pascal square metre per kilogram"),
	P_P80("P80", "millipascal per metre"),
	P_P81("P81", "kilopascal per metre"),
	P_P82("P82", "hectopascal per metre"),
	P_P83("P83", "standard atmosphere per metre"),
	P_P84("P84", "technical atmosphere per metre"),
	P_P85("P85", "torr per metre"),
	P_P86("P86", "psi per inch"),
	P_P87("P87", "cubic metre per second square metre"),
	P_P88("P88", "rhe"),
	P_P89("P89", "pound-force foot per inch"),
	P_P90("P90", "pound-force inch per inch"),
	P_P91("P91", "perm (0 ºC)"),
	P_P92("P92", "perm (23 ºC)"),
	P_P93("P93", "byte per second"),
	P_P94("P94", "kilobyte per second"),
	P_P95("P95", "megabyte per second"),
	P_P96("P96", "reciprocal volt"),
	P_P97("P97", "reciprocal radian"),
	P_P98("P98", "pascal to the power sum of stoichiometric numbers"),
	P_P99("P99", "mole per cubiv metre to the power sum of stoichiometric numbers"),
	P_PAL("PAL", "pascal"),
	P_PD("PD", "pad"),
	P_PFL("PFL", "proof litre"),
	P_PGL("PGL", "proof gallon"),
	P_PI("PI", "pitch"),
	P_PLA("PLA", "degree Plato"),
	P_PO("PO", "pound per inch of length"),
	P_PQ("PQ", "page per inch"),
	P_PR("PR", "pair"),
	P_PS("PS", "pound-force per square inch"),
	P_PTD("PTD", "dry pint (US)"),
	P_PTI("PTI", "pint (UK)"),
	P_PTL("PTL", "liquid pint (US)"),
	P_PTN("PTN", "portion"),
	P_Q10("Q10", "joule per tesla"),
	P_Q11("Q11", "erlang"),
	P_Q12("Q12", "octet"),
	P_Q13("Q13", "octet per second"),
	P_Q14("Q14", "shannon"),
	P_Q15("Q15", "hartley"),
	P_Q16("Q16", "natural unit of information"),
	P_Q17("Q17", "shannon per second"),
	P_Q18("Q18", "hartley per second"),
	P_Q19("Q19", "natural unit of information per second"),
	P_Q20("Q20", "second per kilogramm"),
	P_Q21("Q21", "watt square metre"),
	P_Q22("Q22", "second per radian cubic metre"),
	P_Q23("Q23", "weber to the power minus one"),
	P_Q24("Q24", "reciprocal inch"),
	P_Q25("Q25", "dioptre"),
	P_Q26("Q26", "one per one"),
	P_Q27("Q27", "newton metre per metre"),
	P_Q28("Q28", "kilogram per square metre pascal second"),
	P_Q29("Q29", "microgram per hectogram"),
	P_Q30("Q30", "pH (potential of Hydrogen)"),
	P_Q31("Q31", "kilojoule per gram"),
	P_Q32("Q32", "femtolitre"),
	P_Q33("Q33", "picolitre"),
	P_Q34("Q34", "nanolitre"),
	P_Q35("Q35", "megawatts per minute"),
	P_Q36("Q36", "square metre per cubic metre"),
	P_Q37("Q37", "Standard cubic metre per day"),
	P_Q38("Q38", "Standard cubic metre per hour"),
	P_Q39("Q39", "Normalized cubic metre per day"),
	P_Q40("Q40", "Normalized cubic metre per hour"),
	P_Q41("Q41", "Joule per normalised cubic metre"),
	P_Q42("Q42", "Joule per standard cubic metre"),
	P_Q3("Q3", "meal"),
	P_QA("QA", "page - facsimile"),
	P_QAN("QAN", "quarter (of a year)"),
	P_QB("QB", "page - hardcopy"),
	P_QR("QR", "quire"),
	P_QTD("QTD", "dry quart (US)"),
	P_QTI("QTI", "quart (UK)"),
	P_QTL("QTL", "liquid quart (US)"),
	P_QTR("QTR", "quarter (UK)"),
	P_R1("R1", "pica"),
	P_R9("R9", "thousand cubic metre"),
	P_RH("RH", "running or operating hour"),
	P_RM("RM", "ream"),
	P_ROM("ROM", "room"),
	P_RP("RP", "pound per ream"),
	P_RPM("RPM", "revolutions per minute"),
	P_RPS("RPS", "revolutions per second"),
	P_RT("RT", "revenue ton mile"),
	P_S3("S3", "square foot per second"),
	P_S4("S4", "square metre per second"),
	P_SAN("SAN", "half year (6 months)"),
	P_SCO("SCO", "score"),
	P_SCR("SCR", "scruple"),
	P_SEC("SEC", "second [unit of time]"),
	P_SET("SET", "set"),
	P_SG("SG", "segment"),
	P_SIE("SIE", "siemens"),
	P_SM3("SM3", "Standard cubic metre"),
	P_SMI("SMI", "mile (statute mile)"),
	P_SQ("SQ", "square"),
	P_SQR("SQR", "square, roofing"),
	P_SR("SR", "strip"),
	P_STC("STC", "stick"),
	P_STI("STI", "stone (UK)"),
	P_STK("STK", "stick, cigarette"),
	P_STL("STL", "standard litre"),
	P_STN("STN", "ton (US) or short ton (UK/US)"),
	P_STW("STW", "straw"),
	P_SW("SW", "skein"),
	P_SX("SX", "shipment"),
	P_SYR("SYR", "syringe"),
	P_T0("T0", "telecommunication line in service"),
	P_T3("T3", "thousand piece"),
	P_TAH("TAH", "kiloampere hour (thousand ampere hour)"),
	P_TAN("TAN", "total acid number"),
	P_TI("TI", "thousand square inch"),
	P_TIC("TIC", "metric ton, including container"),
	P_TIP("TIP", "metric ton, including inner packaging"),
	P_TKM("TKM", "tonne kilometre"),
	P_TMS("TMS", "kilogram of imported meat, less offal"),
	P_TNE("TNE", "tonne (metric ton)"),
	P_TP("TP", "ten pack"),
	P_TPI("TPI", "teeth per inch"),
	P_TPR("TPR", "ten pair"),
	P_TQD("TQD", "thousand cubic metre per day"),
	P_TRL("TRL", "trillion (EUR)"),
	P_TST("TST", "ten set"),
	P_TTS("TTS", "ten thousand sticks"),
	P_U1("U1", "treatment"),
	P_U2("U2", "tablet"),
	P_UB("UB", "telecommunication line in service average"),
	P_UC("UC", "telecommunication port"),
	P_VA("VA", "volt - ampere per kilogram"),
	P_VLT("VLT", "volt"),
	P_VP("VP", "percent volume"),
	P_W2("W2", "wet kilo"),
	P_WA("WA", "watt per kilogram"),
	P_WB("WB", "wet pound"),
	P_WCD("WCD", "cord"),
	P_WE("WE", "wet ton"),
	P_WEB("WEB", "weber"),
	P_WEE("WEE", "week"),
	P_WG("WG", "wine gallon"),
	P_WHR("WHR", "watt hour"),
	P_WM("WM", "working month"),
	P_WSD("WSD", "standard"),
	P_WTT("WTT", "watt"),
	P_X1("X1", "Gunter's chain"),
	P_YDK("YDK", "square yard"),
	P_YDQ("YDQ", "cubic yard"),
	P_YRD("YRD", "yard"),
	P_Z11("Z11", "hanging container"),
	P_Z9("Z9", "nanomole"),
	P_ZP("ZP", "page"),
	P_ZZ("ZZ", "mutually defined"),
	P_X1A("X1A", "Drum, steel"),
	P_X1B("X1B", "Drum, aluminium"),
	P_X1D("X1D", "Drum, plywood"),
	P_X1F("X1F", "Container, flexible"),
	P_X1G("X1G", "Drum, fibre"),
	P_X1W("X1W", "Drum, wooden"),
	P_X2C("X2C", "Barrel, wooden"),
	P_X3A("X3A", "Jerrican, steel"),
	P_X3H("X3H", "Jerrican, plastic"),
	P_X43("X43", "Bag, super bulk"),
	P_X44("X44", "Bag, polybag"),
	P_X4A("X4A", "Box, steel"),
	P_X4B("X4B", "Box, aluminium"),
	P_X4C("X4C", "Box, natural wood"),
	P_X4D("X4D", "Box, plywood"),
	P_X4F("X4F", "Box, reconstituted wood"),
	P_X4G("X4G", "Box, fibreboard"),
	P_X4H("X4H", "Box, plastic"),
	P_X5H("X5H", "Bag, woven plastic"),
	P_X5L("X5L", "Bag, textile"),
	P_X5M("X5M", "Bag, paper"),
	P_X6H("X6H", "Composite packaging, plastic receptacle"),
	P_X6P("X6P", "Composite packaging, glass receptacle"),
	P_X7A("X7A", "Case, car"),
	P_X7B("X7B", "Case, wooden"),
	P_X8A("X8A", "Pallet, wooden"),
	P_X8B("X8B", "Crate, wooden"),
	P_X8C("X8C", "Bundle, wooden"),
	P_XAA("XAA", "Intermediate bulk container, rigid plastic"),
	P_XAB("XAB", "Receptacle, fibre"),
	P_XAC("XAC", "Receptacle, paper"),
	P_XAD("XAD", "Receptacle, wooden"),
	P_XAE("XAE", "Aerosol"),
	P_XAF("XAF", "Pallet, modular, collars 80cms * 60cms"),
	P_XAG("XAG", "Pallet, shrinkwrapped"),
	P_XAH("XAH", "Pallet, 100cms * 110cms"),
	P_XAI("XAI", "Clamshell"),
	P_XAJ("XAJ", "Cone"),
	P_XAL("XAL", "Ball"),
	P_XAM("XAM", "Ampoule, non-protected"),
	P_XAP("XAP", "Ampoule, protected"),
	P_XAT("XAT", "Atomizer"),
	P_XAV("XAV", "Capsule"),
	P_XB4("XB4", "Belt"),
	P_XBA("XBA", "Barrel"),
	P_XBB("XBB", "Bobbin"),
	P_XBC("XBC", "Bottlecrate / bottlerack"),
	P_XBD("XBD", "Board"),
	P_XBE("XBE", "Bundle"),
	P_XBF("XBF", "Balloon, non-protected"),
	P_XBG("XBG", "Bag"),
	P_XBH("XBH", "Bunch"),
	P_XBI("XBI", "Bin"),
	P_XBJ("XBJ", "Bucket"),
	P_XBK("XBK", "Basket"),
	P_XBL("XBL", "Bale, compressed"),
	P_XBM("XBM", "Basin"),
	P_XBN("XBN", "Bale, non-compressed"),
	P_XBO("XBO", "Bottle, non-protected, cylindrical"),
	P_XBP("XBP", "Balloon, protected"),
	P_XBQ("XBQ", "Bottle, protected cylindrical"),
	P_XBR("XBR", "Bar"),
	P_XBS("XBS", "Bottle, non-protected, bulbous"),
	P_XBT("XBT", "Bolt"),
	P_XBU("XBU", "Butt"),
	P_XBV("XBV", "Bottle, protected bulbous"),
	P_XBW("XBW", "Box, for liquids"),
	P_XBX("XBX", "Box"),
	P_XBY("XBY", "Board, in bundle/bunch/truss"),
	P_XBZ("XBZ", "Bars, in bundle/bunch/truss"),
	P_XCA("XCA", "Can, rectangular"),
	P_XCB("XCB", "Crate, beer"),
	P_XCC("XCC", "Churn"),
	P_XCD("XCD", "Can, with handle and spout"),
	P_XCE("XCE", "Creel"),
	P_XCF("XCF", "Coffer"),
	P_XCG("XCG", "Cage"),
	P_XCH("XCH", "Chest"),
	P_XCI("XCI", "Canister"),
	P_XCJ("XCJ", "Coffin"),
	P_XCK("XCK", "Cask"),
	P_XCL("XCL", "Coil"),
	P_XCM("XCM", "Card"),
	P_XCN("XCN", "Container, not otherwise specified as transport equipment"),
	P_XCO("XCO", "Carboy, non-protected"),
	P_XCP("XCP", "Carboy, protected"),
	P_XCQ("XCQ", "Cartridge"),
	P_XCR("XCR", "Crate"),
	P_XCS("XCS", "Case"),
	P_XCT("XCT", "Carton"),
	P_XCU("XCU", "Cup"),
	P_XCV("XCV", "Cover"),
	P_XCW("XCW", "Cage, roll"),
	P_XCX("XCX", "Can, cylindrical"),
	P_XCY("XCY", "Cylinder"),
	P_XCZ("XCZ", "Canvas"),
	P_XDA("XDA", "Crate, multiple layer, plastic"),
	P_XDB("XDB", "Crate, multiple layer, wooden"),
	P_XDC("XDC", "Crate, multiple layer, cardboard"),
	P_XDG("XDG", "Cage, Commonwealth Handling Equipment Pool (CHEP)"),
	P_XDH("XDH", "Box, Commonwealth Handling Equipment Pool (CHEP), Eurobox"),
	P_XDI("XDI", "Drum, iron"),
	P_XDJ("XDJ", "Demijohn, non-protected"),
	P_XDK("XDK", "Crate, bulk, cardboard"),
	P_XDL("XDL", "Crate, bulk, plastic"),
	P_XDM("XDM", "Crate, bulk, wooden"),
	P_XDN("XDN", "Dispenser"),
	P_XDP("XDP", "Demijohn, protected"),
	P_XDR("XDR", "Drum"),
	P_XDS("XDS", "Tray, one layer no cover, plastic"),
	P_XDT("XDT", "Tray, one layer no cover, wooden"),
	P_XDU("XDU", "Tray, one layer no cover, polystyrene"),
	P_XDV("XDV", "Tray, one layer no cover, cardboard"),
	P_XDW("XDW", "Tray, two layers no cover, plastic tray"),
	P_XDX("XDX", "Tray, two layers no cover, wooden"),
	P_XDY("XDY", "Tray, two layers no cover, cardboard"),
	P_XEC("XEC", "Bag, plastic"),
	P_XED("XED", "Case, with pallet base"),
	P_XEE("XEE", "Case, with pallet base, wooden"),
	P_XEF("XEF", "Case, with pallet base, cardboard"),
	P_XEG("XEG", "Case, with pallet base, plastic"),
	P_XEH("XEH", "Case, with pallet base, metal"),
	P_XEI("XEI", "Case, isothermic"),
	P_XEN("XEN", "Envelope"),
	P_XFB("XFB", "Flexibag"),
	P_XFC("XFC", "Crate, fruit"),
	P_XFD("XFD", "Crate, framed"),
	P_XFE("XFE", "Flexitank"),
	P_XFI("XFI", "Firkin"),
	P_XFL("XFL", "Flask"),
	P_XFO("XFO", "Footlocker"),
	P_XFP("XFP", "Filmpack"),
	P_XFR("XFR", "Frame"),
	P_XFT("XFT", "Foodtainer"),
	P_XFW("XFW", "Cart, flatbed"),
	P_XFX("XFX", "Bag, flexible container"),
	P_XGB("XGB", "Bottle, gas"),
	P_XGI("XGI", "Girder"),
	P_XGL("XGL", "Container, gallon"),
	P_XGR("XGR", "Receptacle, glass"),
	P_XGU("XGU", "Tray, containing horizontally stacked flat items"),
	P_XGY("XGY", "Bag, gunny"),
	P_XGZ("XGZ", "Girders, in bundle/bunch/truss"),
	P_XHA("XHA", "Basket, with handle, plastic"),
	P_XHB("XHB", "Basket, with handle, wooden"),
	P_XHC("XHC", "Basket, with handle, cardboard"),
	P_XHG("XHG", "Hogshead"),
	P_XHN("XHN", "Hanger"),
	P_XHR("XHR", "Hamper"),
	P_XIA("XIA", "Package, display, wooden"),
	P_XIB("XIB", "Package, display, cardboard"),
	P_XIC("XIC", "Package, display, plastic"),
	P_XID("XID", "Package, display, metal"),
	P_XIE("XIE", "Package, show"),
	P_XIF("XIF", "Package, flow"),
	P_XIG("XIG", "Package, paper wrapped"),
	P_XIH("XIH", "Drum, plastic"),
	P_XIK("XIK", "Package, cardboard, with bottle grip-holes"),
	P_XIL("XIL", "Tray, rigid, lidded stackable (CEN TS 14482:2002)"),
	P_XIN("XIN", "Ingot"),
	P_XIZ("XIZ", "Ingots, in bundle/bunch/truss"),
	P_XJB("XJB", "Bag, jumbo"),
	P_XJC("XJC", "Jerrican, rectangular"),
	P_XJG("XJG", "Jug"),
	P_XJR("XJR", "Jar"),
	P_XJT("XJT", "Jutebag"),
	P_XJY("XJY", "Jerrican, cylindrical"),
	P_XKG("XKG", "Keg"),
	P_XKI("XKI", "Kit"),
	P_XLE("XLE", "Luggage"),
	P_XLG("XLG", "Log"),
	P_XLT("XLT", "Lot"),
	P_XLU("XLU", "Lug"),
	P_XLV("XLV", "Liftvan"),
	P_XLZ("XLZ", "Logs, in bundle/bunch/truss"),
	P_XMA("XMA", "Crate, metal"),
	P_XMB("XMB", "Bag, multiply"),
	P_XMC("XMC", "Crate, milk"),
	P_XME("XME", "Container, metal"),
	P_XMR("XMR", "Receptacle, metal"),
	P_XMS("XMS", "Sack, multi-wall"),
	P_XMT("XMT", "Mat"),
	P_XMW("XMW", "Receptacle, plastic wrapped"),
	P_XMX("XMX", "Matchbox"),
	P_XNA("XNA", "Not available"),
	P_XNE("XNE", "Unpacked or unpackaged"),
	P_XNF("XNF", "Unpacked or unpackaged, single unit"),
	P_XNG("XNG", "Unpacked or unpackaged, multiple units"),
	P_XNS("XNS", "Nest"),
	P_XNT("XNT", "Net"),
	P_XNU("XNU", "Net, tube, plastic"),
	P_XNV("XNV", "Net, tube, textile"),
	P_XO1("XO1", "Two sided cage on wheels with fixing strap"),
	P_XO2("XO2", "Trolley"),
	P_XO3("XO3", "Oneway pallet ISO 0 - 1/2 EURO Pallet"),
	P_XO4("XO4", "Oneway pallet ISO 1 - 1/1 EURO Pallet"),
	P_XO5("XO5", "Oneway pallet ISO 2 - 2/1 EURO Pallet"),
	P_XO6("XO6", "Pallet with exceptional dimensions"),
	P_XO7("XO7", "Wooden pallet 40 cm x 80 cm"),
	P_XO8("XO8", "Plastic pallet SRS 60 cm x 80 cm"),
	P_XO9("XO9", "Plastic pallet SRS 80 cm x 120 cm"),
	P_XOA("XOA", "Pallet, CHEP 40 cm x 60 cm"),
	P_XOB("XOB", "Pallet, CHEP 80 cm x 120 cm"),
	P_XOC("XOC", "Pallet, CHEP 100 cm x 120 cm"),
	P_XOD("XOD", "Pallet, AS 4068-1993"),
	P_XOE("XOE", "Pallet, ISO T11"),
	P_XOF("XOF", "Platform, unspecified weight or dimension"),
	P_XOG("XOG", "Pallet ISO 0 - 1/2 EURO Pallet"),
	P_XOH("XOH", "Pallet ISO 1 - 1/1 EURO Pallet"),
	P_XOI("XOI", "Pallet ISO 2 – 2/1 EURO Pallet"),
	P_XOK("XOK", "Block"),
	P_XOJ("XOJ", "1/4 EURO Pallet"),
	P_XOL("XOL", "1/8 EURO Pallet"),
	P_XOM("XOM", "Synthetic pallet ISO 1"),
	P_XON("XON", "Synthetic pallet ISO 2"),
	P_XOP("XOP", "Wholesaler pallet"),
	P_XOQ("XOQ", "Pallet 80 X 100 cm"),
	P_XOR("XOR", "Pallet 60 X 100 cm"),
	P_XOS("XOS", "Oneway pallet"),
	P_XOV("XOV", "Returnable pallet"),
	P_XOW("XOW", "Large bag, pallet sized"),
	P_XOT("XOT", "Octabin"),
	P_XOU("XOU", "Container, outer"),
	P_XOX("XOX", "A wheeled pallet with raised rim (81 x 67 x 135)"),
	P_XOY("XOY", "A Wheeled pallet with raised rim (81 x 72 x 135)"),
	P_XOZ("XOZ", "Wheeled pallet with raised rim ( 81 x 60 x 16)"),
	P_XP1("XP1", "CHEP pallet 60 cm x 80 cm"),
	P_XP2("XP2", "Pan"),
	P_XP3("XP3", "LPR pallet 60 cm x 80 cm"),
	P_XP4("XP4", "LPR pallet 80 cm x 120 cm"),
	P_XPA("XPA", "Packet"),
	P_XPB("XPB", "Pallet, box Combined open-ended box and pallet"),
	P_XPC("XPC", "Parcel"),
	P_XPD("XPD", "Pallet, modular, collars 80cms * 100cms"),
	P_XPE("XPE", "Pallet, modular, collars 80cms * 120cms"),
	P_XPF("XPF", "Pen"),
	P_XPG("XPG", "Plate"),
	P_XPH("XPH", "Pitcher"),
	P_XPI("XPI", "Pipe"),
	P_XPJ("XPJ", "Punnet"),
	P_XPK("XPK", "Package"),
	P_XPL("XPL", "Pail"),
	P_XPN("XPN", "Plank"),
	P_XPO("XPO", "Pouch"),
	P_XPP("XPP", "Piece"),
	P_XPR("XPR", "Receptacle, plastic"),
	P_XPT("XPT", "Pot"),
	P_XPU("XPU", "Tray"),
	P_XPV("XPV", "Pipes, in bundle/bunch/truss"),
	P_XPX("XPX", "Pallet"),
	P_XPY("XPY", "Plates, in bundle/bunch/truss"),
	P_XPZ("XPZ", "Planks, in bundle/bunch/truss"),
	P_XQA("XQA", "Drum, steel, non-removable head"),
	P_XQB("XQB", "Drum, steel, removable head"),
	P_XQC("XQC", "Drum, aluminium, non-removable head"),
	P_XQD("XQD", "Drum, aluminium, removable head"),
	P_XQF("XQF", "Drum, plastic, non-removable head"),
	P_XQG("XQG", "Drum, plastic, removable head"),
	P_XQH("XQH", "Barrel, wooden, bung type"),
	P_XQJ("XQJ", "Barrel, wooden, removable head"),
	P_XQK("XQK", "Jerrican, steel, non-removable head"),
	P_XQL("XQL", "Jerrican, steel, removable head"),
	P_XQM("XQM", "Jerrican, plastic, non-removable head"),
	P_XQN("XQN", "Jerrican, plastic, removable head"),
	P_XQP("XQP", "Box, wooden, natural wood, ordinary"),
	P_XQQ("XQQ", "Box, wooden, natural wood, with sift proof walls"),
	P_XQR("XQR", "Box, plastic, expanded"),
	P_XQS("XQS", "Box, plastic, solid"),
	P_XRD("XRD", "Rod"),
	P_XRG("XRG", "Ring"),
	P_XRJ("XRJ", "Rack, clothing hanger"),
	P_XRK("XRK", "Rack"),
	P_XRL("XRL", "Reel"),
	P_XRO("XRO", "Roll"),
	P_XRT("XRT", "Rednet"),
	P_XRZ("XRZ", "Rods, in bundle/bunch/truss"),
	P_XSA("XSA", "Sack"),
	P_XSB("XSB", "Slab"),
	P_XSC("XSC", "Crate, shallow"),
	P_XSD("XSD", "Spindle"),
	P_XSE("XSE", "Sea-chest"),
	P_XSH("XSH", "Sachet"),
	P_XSI("XSI", "Skid"),
	P_XSK("XSK", "Case, skeleton"),
	P_XSL("XSL", "Slipsheet"),
	P_XSM("XSM", "Sheetmetal"),
	P_XSO("XSO", "Spool"),
	P_XSP("XSP", "Sheet, plastic wrapping"),
	P_XSS("XSS", "Case, steel"),
	P_XST("XST", "Sheet"),
	P_XSU("XSU", "Suitcase"),
	P_XSV("XSV", "Envelope, steel"),
	P_XSW("XSW", "Shrinkwrapped"),
	P_XSX("XSX", "Set"),
	P_XSY("XSY", "Sleeve"),
	P_XSZ("XSZ", "Sheets, in bundle/bunch/truss"),
	P_XT1("XT1", "Tablet"),
	P_XTB("XTB", "Tub"),
	P_XTC("XTC", "Tea-chest"),
	P_XTD("XTD", "Tube, collapsible"),
	P_XTE("XTE", "Tyre"),
	P_XTG("XTG", "Tank container, generic"),
	P_XTI("XTI", "Tierce"),
	P_XTK("XTK", "Tank, rectangular"),
	P_XTL("XTL", "Tub, with lid"),
	P_XTN("XTN", "Tin"),
	P_XTO("XTO", "Tun"),
	P_XTR("XTR", "Trunk"),
	P_XTS("XTS", "Truss"),
	P_XTT("XTT", "Bag, tote"),
	P_XTU("XTU", "Tube"),
	P_XTV("XTV", "Tube, with nozzle"),
	P_XTW("XTW", "Pallet, triwall"),
	P_XTY("XTY", "Tank, cylindrical"),
	P_XTZ("XTZ", "Tubes, in bundle/bunch/truss"),
	P_XUC("XUC", "Uncaged"),
	P_XUN("XUN", "Unit"),
	P_XVA("XVA", "Vat"),
	P_XVG("XVG", "Bulk, gas (at 1031 mbar and 15°C)"),
	P_XVI("XVI", "Vial"),
	P_XVK("XVK", "Vanpack"),
	P_XVL("XVL", "Bulk, liquid"),
	P_XVO("XVO", "Bulk, solid, large particles (“nodules”)"),
	P_XVP("XVP", "Vacuum-packed"),
	P_XVQ("XVQ", "Bulk, liquefied gas (at abnormal temperature/pressure)"),
	P_XVN("XVN", "Vehicle"),
	P_XVR("XVR", "Bulk, solid, granular particles (“grains”)"),
	P_XVS("XVS", "Bulk, scrap metal"),
	P_XVY("XVY", "Bulk, solid, fine particles (“powders”)"),
	P_XWA("XWA", "Intermediate bulk container"),
	P_XWB("XWB", "Wickerbottle"),
	P_XWC("XWC", "Intermediate bulk container, steel"),
	P_XWD("XWD", "Intermediate bulk container, aluminium"),
	P_XWF("XWF", "Intermediate bulk container, metal"),
	P_XWG("XWG", "Intermediate bulk container, steel, pressurised > 10 kpa"),
	P_XWH("XWH", "Intermediate bulk container, aluminium, pressurised > 10 kpa"),
	P_XWJ("XWJ", "Intermediate bulk container, metal, pressure 10 kpa"),
	P_XWK("XWK", "Intermediate bulk container, steel, liquid"),
	P_XWL("XWL", "Intermediate bulk container, aluminium, liquid"),
	P_XWM("XWM", "Intermediate bulk container, metal, liquid"),
	P_XWN("XWN", "Intermediate bulk container, woven plastic, without coat/liner"),
	P_XWP("XWP", "Intermediate bulk container, woven plastic, coated"),
	P_XWQ("XWQ", "Intermediate bulk container, woven plastic, with liner"),
	P_XWR("XWR", "Intermediate bulk container, woven plastic, coated and liner"),
	P_XWS("XWS", "Intermediate bulk container, plastic film"),
	P_XWT("XWT", "Intermediate bulk container, textile with out coat/liner"),
	P_XWU("XWU", "Intermediate bulk container, natural wood, with inner liner"),
	P_XWV("XWV", "Intermediate bulk container, textile, coated"),
	P_XWW("XWW", "Intermediate bulk container, textile, with liner"),
	P_XWX("XWX", "Intermediate bulk container, textile, coated and liner"),
	P_XWY("XWY", "Intermediate bulk container, plywood, with inner liner"),
	P_XWZ("XWZ", "Intermediate bulk container, reconstituted wood, with inner liner"),
	P_XXA("XXA", "Bag, woven plastic, without inner coat/liner"),
	P_XXB("XXB", "Bag, woven plastic, sift proof"),
	P_XXC("XXC", "Bag, woven plastic, water resistant"),
	P_XXD("XXD", "Bag, plastics film"),
	P_XXF("XXF", "Bag, textile, without inner coat/liner"),
	P_XXG("XXG", "Bag, textile, sift proof"),
	P_XXH("XXH", "Bag, textile, water resistant"),
	P_XXJ("XXJ", "Bag, paper, multi-wall"),
	P_XXK("XXK", "Bag, paper, multi-wall, water resistant"),
	P_XYA("XYA", "Composite packaging, plastic receptacle in steel drum"),
	P_XYB("XYB", "Composite packaging, plastic receptacle in steel crate box"),
	P_XYC("XYC", "Composite packaging, plastic receptacle in aluminium drum"),
	P_XYD("XYD", "Composite packaging, plastic receptacle in aluminium crate"),
	P_XYF("XYF", "Composite packaging, plastic receptacle in wooden box"),
	P_XYG("XYG", "Composite packaging, plastic receptacle in plywood drum"),
	P_XYH("XYH", "Composite packaging, plastic receptacle in plywood box"),
	P_XYJ("XYJ", "Composite packaging, plastic receptacle in fibre drum"),
	P_XYK("XYK", "Composite packaging, plastic receptacle in fibreboard box"),
	P_XYL("XYL", "Composite packaging, plastic receptacle in plastic drum"),
	P_XYM("XYM", "Composite packaging, plastic receptacle in solid plastic box"),
	P_XYN("XYN", "Composite packaging, glass receptacle in steel drum"),
	P_XYP("XYP", "Composite packaging, glass receptacle in steel crate box"),
	P_XYQ("XYQ", "Composite packaging, glass receptacle in aluminium drum"),
	P_XYR("XYR", "Composite packaging, glass receptacle in aluminium crate"),
	P_XYS("XYS", "Composite packaging, glass receptacle in wooden box"),
	P_XYT("XYT", "Composite packaging, glass receptacle in plywood drum"),
	P_XYV("XYV", "Composite packaging, glass receptacle in wickerwork hamper"),
	P_XYW("XYW", "Composite packaging, glass receptacle in fibre drum"),
	P_XYX("XYX", "Composite packaging, glass receptacle in fibreboard box"),
	P_XYY("XYY", "Composite packaging, glass receptacle in expandable plastic pack"),
	P_XYZ("XYZ", "Composite packaging, glass receptacle in solid plastic pack"),
	P_XZA("XZA", "Intermediate bulk container, paper, multi-wall"),
	P_XZB("XZB", "Bag, large"),
	P_XZC("XZC", "Intermediate bulk container, paper, multi-wall, water resistant"),
	P_XZD("XZD", "Intermediate bulk container, rigid plastic, with structural equipment, solids"),
	P_XZF("XZF", "Intermediate bulk container, rigid plastic, freestanding, solids"),
	P_XZG("XZG", "Intermediate bulk container, rigid plastic, with structural equipment, pressurised"),
	P_XZH("XZH", "Intermediate bulk container, rigid plastic, freestanding, pressurised"),
	P_XZJ("XZJ", "Intermediate bulk container, rigid plastic, with structural equipment, liquids"),
	P_XZK("XZK", "Intermediate bulk container, rigid plastic, freestanding, liquids"),
	P_XZL("XZL", "Intermediate bulk container, composite, rigid plastic, solids"),
	P_XZM("XZM", "Intermediate bulk container, composite, flexible plastic, solids"),
	P_XZN("XZN", "Intermediate bulk container, composite, rigid plastic, pressurised"),
	P_XZP("XZP", "Intermediate bulk container, composite, flexible plastic, pressurised"),
	P_XZQ("XZQ", "Intermediate bulk container, composite, rigid plastic, liquids"),
	P_XZR("XZR", "Intermediate bulk container, composite, flexible plastic, liquids"),
	P_XZS("XZS", "Intermediate bulk container, composite"),
	P_XZT("XZT", "Intermediate bulk container, fibreboard"),
	P_XZU("XZU", "Intermediate bulk container, flexible"),
	P_XZV("XZV", "Intermediate bulk container, metal, other than steel"),
	P_XZW("XZW", "Intermediate bulk container, natural wood"),
	P_XZX("XZX", "Intermediate bulk container, plywood"),
	P_XZY("XZY", "Intermediate bulk container, reconstituted wood"),
	P_XZZ("XZZ", "Mutually defined");

	private final String code;
	private final String fullName;

	Unecerec20(String code, String fullName) {
		this.code = code;
		this.fullName = fullName;
	}

	public String getCode(){
		return code;
	}

	public String getFullName(){
		return fullName;
	}
}
